// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"

	"github.com/makesalekz/platform-billing/internal/biz"
	"github.com/makesalekz/platform-billing/internal/conf"
	"github.com/makesalekz/platform-billing/internal/data"
	"github.com/makesalekz/platform-billing/internal/server"
	"github.com/makesalekz/platform-billing/internal/service"
)

func wireApp(bc *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bc, logger)
	if err != nil {
		return nil, nil, err
	}

	natsConn, natsCleanup, err := data.NewNatsClient(bc)
	if err != nil {
		cleanup()
		return nil, nil, err
	}

	tenantsClient, tenantsCleanup, err := data.NewTenantsClientFromConf(bc, logger)
	if err != nil {
		natsCleanup()
		cleanup()
		return nil, nil, err
	}

	commissionsRepo := data.NewCommissionsRepo(dataData)
	exclusionsRepo := data.NewExclusionsRepo(dataData)
	saleEventsRepo := data.NewSaleEventsRepo(dataData)

	billingUsecase := biz.NewBillingUsecase(logger, commissionsRepo, exclusionsRepo, saleEventsRepo, tenantsClient, natsConn)

	// Start NATS consumer for sales events
	_, consumerCleanup, err := biz.NewConsumer(natsConn, billingUsecase, logger)
	if err != nil {
		tenantsCleanup()
		natsCleanup()
		cleanup()
		return nil, nil, err
	}

	platformBillingService := service.NewPlatformBillingService(billingUsecase)

	grpcServer := server.NewGRPCServer(bc, platformBillingService)

	app := newApp(logger, grpcServer)

	return app, func() {
		consumerCleanup()
		tenantsCleanup()
		natsCleanup()
		cleanup()
	}, nil
}
