// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/makesalekz/platform-billing/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/makesalekz/platform-billing/ent/commission"
	"github.com/makesalekz/platform-billing/ent/exclusion"
	"github.com/makesalekz/platform-billing/ent/saleevent"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Commission is the client for interacting with the Commission builders.
	Commission *CommissionClient
	// Exclusion is the client for interacting with the Exclusion builders.
	Exclusion *ExclusionClient
	// SaleEvent is the client for interacting with the SaleEvent builders.
	SaleEvent *SaleEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Commission = NewCommissionClient(c.config)
	c.Exclusion = NewExclusionClient(c.config)
	c.SaleEvent = NewSaleEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Commission: NewCommissionClient(cfg),
		Exclusion:  NewExclusionClient(cfg),
		SaleEvent:  NewSaleEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		Commission: NewCommissionClient(cfg),
		Exclusion:  NewExclusionClient(cfg),
		SaleEvent:  NewSaleEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Commission.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Commission.Use(hooks...)
	c.Exclusion.Use(hooks...)
	c.SaleEvent.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Commission.Intercept(interceptors...)
	c.Exclusion.Intercept(interceptors...)
	c.SaleEvent.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CommissionMutation:
		return c.Commission.mutate(ctx, m)
	case *ExclusionMutation:
		return c.Exclusion.mutate(ctx, m)
	case *SaleEventMutation:
		return c.SaleEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CommissionClient is a client for the Commission schema.
type CommissionClient struct {
	config
}

// NewCommissionClient returns a client for the Commission from the given config.
func NewCommissionClient(c config) *CommissionClient {
	return &CommissionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `commission.Hooks(f(g(h())))`.
func (c *CommissionClient) Use(hooks ...Hook) {
	c.hooks.Commission = append(c.hooks.Commission, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `commission.Intercept(f(g(h())))`.
func (c *CommissionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Commission = append(c.inters.Commission, interceptors...)
}

// Create returns a builder for creating a Commission entity.
func (c *CommissionClient) Create() *CommissionCreate {
	mutation := newCommissionMutation(c.config, OpCreate)
	return &CommissionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Commission entities.
func (c *CommissionClient) CreateBulk(builders ...*CommissionCreate) *CommissionCreateBulk {
	return &CommissionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CommissionClient) MapCreateBulk(slice any, setFunc func(*CommissionCreate, int)) *CommissionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CommissionCreateBulk{err: fmt.Errorf("calling to CommissionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CommissionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CommissionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Commission.
func (c *CommissionClient) Update() *CommissionUpdate {
	mutation := newCommissionMutation(c.config, OpUpdate)
	return &CommissionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CommissionClient) UpdateOne(co *Commission) *CommissionUpdateOne {
	mutation := newCommissionMutation(c.config, OpUpdateOne, withCommission(co))
	return &CommissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CommissionClient) UpdateOneID(id int64) *CommissionUpdateOne {
	mutation := newCommissionMutation(c.config, OpUpdateOne, withCommissionID(id))
	return &CommissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Commission.
func (c *CommissionClient) Delete() *CommissionDelete {
	mutation := newCommissionMutation(c.config, OpDelete)
	return &CommissionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CommissionClient) DeleteOne(co *Commission) *CommissionDeleteOne {
	return c.DeleteOneID(co.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CommissionClient) DeleteOneID(id int64) *CommissionDeleteOne {
	builder := c.Delete().Where(commission.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CommissionDeleteOne{builder}
}

// Query returns a query builder for Commission.
func (c *CommissionClient) Query() *CommissionQuery {
	return &CommissionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCommission},
		inters: c.Interceptors(),
	}
}

// Get returns a Commission entity by its id.
func (c *CommissionClient) Get(ctx context.Context, id int64) (*Commission, error) {
	return c.Query().Where(commission.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CommissionClient) GetX(ctx context.Context, id int64) *Commission {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CommissionClient) Hooks() []Hook {
	return c.hooks.Commission
}

// Interceptors returns the client interceptors.
func (c *CommissionClient) Interceptors() []Interceptor {
	return c.inters.Commission
}

func (c *CommissionClient) mutate(ctx context.Context, m *CommissionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CommissionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CommissionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CommissionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CommissionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Commission mutation op: %q", m.Op())
	}
}

// ExclusionClient is a client for the Exclusion schema.
type ExclusionClient struct {
	config
}

// NewExclusionClient returns a client for the Exclusion from the given config.
func NewExclusionClient(c config) *ExclusionClient {
	return &ExclusionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `exclusion.Hooks(f(g(h())))`.
func (c *ExclusionClient) Use(hooks ...Hook) {
	c.hooks.Exclusion = append(c.hooks.Exclusion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `exclusion.Intercept(f(g(h())))`.
func (c *ExclusionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Exclusion = append(c.inters.Exclusion, interceptors...)
}

// Create returns a builder for creating a Exclusion entity.
func (c *ExclusionClient) Create() *ExclusionCreate {
	mutation := newExclusionMutation(c.config, OpCreate)
	return &ExclusionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Exclusion entities.
func (c *ExclusionClient) CreateBulk(builders ...*ExclusionCreate) *ExclusionCreateBulk {
	return &ExclusionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ExclusionClient) MapCreateBulk(slice any, setFunc func(*ExclusionCreate, int)) *ExclusionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ExclusionCreateBulk{err: fmt.Errorf("calling to ExclusionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ExclusionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ExclusionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Exclusion.
func (c *ExclusionClient) Update() *ExclusionUpdate {
	mutation := newExclusionMutation(c.config, OpUpdate)
	return &ExclusionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ExclusionClient) UpdateOne(e *Exclusion) *ExclusionUpdateOne {
	mutation := newExclusionMutation(c.config, OpUpdateOne, withExclusion(e))
	return &ExclusionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ExclusionClient) UpdateOneID(id int64) *ExclusionUpdateOne {
	mutation := newExclusionMutation(c.config, OpUpdateOne, withExclusionID(id))
	return &ExclusionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Exclusion.
func (c *ExclusionClient) Delete() *ExclusionDelete {
	mutation := newExclusionMutation(c.config, OpDelete)
	return &ExclusionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ExclusionClient) DeleteOne(e *Exclusion) *ExclusionDeleteOne {
	return c.DeleteOneID(e.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ExclusionClient) DeleteOneID(id int64) *ExclusionDeleteOne {
	builder := c.Delete().Where(exclusion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ExclusionDeleteOne{builder}
}

// Query returns a query builder for Exclusion.
func (c *ExclusionClient) Query() *ExclusionQuery {
	return &ExclusionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeExclusion},
		inters: c.Interceptors(),
	}
}

// Get returns a Exclusion entity by its id.
func (c *ExclusionClient) Get(ctx context.Context, id int64) (*Exclusion, error) {
	return c.Query().Where(exclusion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ExclusionClient) GetX(ctx context.Context, id int64) *Exclusion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ExclusionClient) Hooks() []Hook {
	return c.hooks.Exclusion
}

// Interceptors returns the client interceptors.
func (c *ExclusionClient) Interceptors() []Interceptor {
	return c.inters.Exclusion
}

func (c *ExclusionClient) mutate(ctx context.Context, m *ExclusionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ExclusionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ExclusionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ExclusionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ExclusionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Exclusion mutation op: %q", m.Op())
	}
}

// SaleEventClient is a client for the SaleEvent schema.
type SaleEventClient struct {
	config
}

// NewSaleEventClient returns a client for the SaleEvent from the given config.
func NewSaleEventClient(c config) *SaleEventClient {
	return &SaleEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `saleevent.Hooks(f(g(h())))`.
func (c *SaleEventClient) Use(hooks ...Hook) {
	c.hooks.SaleEvent = append(c.hooks.SaleEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `saleevent.Intercept(f(g(h())))`.
func (c *SaleEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.SaleEvent = append(c.inters.SaleEvent, interceptors...)
}

// Create returns a builder for creating a SaleEvent entity.
func (c *SaleEventClient) Create() *SaleEventCreate {
	mutation := newSaleEventMutation(c.config, OpCreate)
	return &SaleEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SaleEvent entities.
func (c *SaleEventClient) CreateBulk(builders ...*SaleEventCreate) *SaleEventCreateBulk {
	return &SaleEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SaleEventClient) MapCreateBulk(slice any, setFunc func(*SaleEventCreate, int)) *SaleEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SaleEventCreateBulk{err: fmt.Errorf("calling to SaleEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SaleEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SaleEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SaleEvent.
func (c *SaleEventClient) Update() *SaleEventUpdate {
	mutation := newSaleEventMutation(c.config, OpUpdate)
	return &SaleEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SaleEventClient) UpdateOne(se *SaleEvent) *SaleEventUpdateOne {
	mutation := newSaleEventMutation(c.config, OpUpdateOne, withSaleEvent(se))
	return &SaleEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SaleEventClient) UpdateOneID(id int64) *SaleEventUpdateOne {
	mutation := newSaleEventMutation(c.config, OpUpdateOne, withSaleEventID(id))
	return &SaleEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SaleEvent.
func (c *SaleEventClient) Delete() *SaleEventDelete {
	mutation := newSaleEventMutation(c.config, OpDelete)
	return &SaleEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SaleEventClient) DeleteOne(se *SaleEvent) *SaleEventDeleteOne {
	return c.DeleteOneID(se.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SaleEventClient) DeleteOneID(id int64) *SaleEventDeleteOne {
	builder := c.Delete().Where(saleevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SaleEventDeleteOne{builder}
}

// Query returns a query builder for SaleEvent.
func (c *SaleEventClient) Query() *SaleEventQuery {
	return &SaleEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSaleEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a SaleEvent entity by its id.
func (c *SaleEventClient) Get(ctx context.Context, id int64) (*SaleEvent, error) {
	return c.Query().Where(saleevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SaleEventClient) GetX(ctx context.Context, id int64) *SaleEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SaleEventClient) Hooks() []Hook {
	return c.hooks.SaleEvent
}

// Interceptors returns the client interceptors.
func (c *SaleEventClient) Interceptors() []Interceptor {
	return c.inters.SaleEvent
}

func (c *SaleEventClient) mutate(ctx context.Context, m *SaleEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SaleEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SaleEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SaleEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SaleEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SaleEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Commission, Exclusion, SaleEvent []ent.Hook
	}
	inters struct {
		Commission, Exclusion, SaleEvent []ent.Interceptor
	}
)
