// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/platform-billing/ent/commission"
	"gitlab.calendaria.team/services/platform-billing/ent/enum"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
)

// CommissionUpdate is the builder for updating Commission entities.
type CommissionUpdate struct {
	config
	hooks     []Hook
	mutation  *CommissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CommissionUpdate builder.
func (cu *CommissionUpdate) Where(ps ...predicate.Commission) *CommissionUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CommissionUpdate) SetUpdatedAt(t time.Time) *CommissionUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetPeriodStart sets the "period_start" field.
func (cu *CommissionUpdate) SetPeriodStart(t time.Time) *CommissionUpdate {
	cu.mutation.SetPeriodStart(t)
	return cu
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillablePeriodStart(t *time.Time) *CommissionUpdate {
	if t != nil {
		cu.SetPeriodStart(*t)
	}
	return cu
}

// SetPeriodEnd sets the "period_end" field.
func (cu *CommissionUpdate) SetPeriodEnd(t time.Time) *CommissionUpdate {
	cu.mutation.SetPeriodEnd(t)
	return cu
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillablePeriodEnd(t *time.Time) *CommissionUpdate {
	if t != nil {
		cu.SetPeriodEnd(*t)
	}
	return cu
}

// SetGmv sets the "gmv" field.
func (cu *CommissionUpdate) SetGmv(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetGmv()
	cu.mutation.SetGmv(d)
	return cu
}

// SetNillableGmv sets the "gmv" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableGmv(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetGmv(*d)
	}
	return cu
}

// AddGmv adds d to the "gmv" field.
func (cu *CommissionUpdate) AddGmv(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddGmv(d)
	return cu
}

// ClearGmv clears the value of the "gmv" field.
func (cu *CommissionUpdate) ClearGmv() *CommissionUpdate {
	cu.mutation.ClearGmv()
	return cu
}

// SetExcludedAmount sets the "excluded_amount" field.
func (cu *CommissionUpdate) SetExcludedAmount(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetExcludedAmount()
	cu.mutation.SetExcludedAmount(d)
	return cu
}

// SetNillableExcludedAmount sets the "excluded_amount" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableExcludedAmount(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetExcludedAmount(*d)
	}
	return cu
}

// AddExcludedAmount adds d to the "excluded_amount" field.
func (cu *CommissionUpdate) AddExcludedAmount(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddExcludedAmount(d)
	return cu
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (cu *CommissionUpdate) ClearExcludedAmount() *CommissionUpdate {
	cu.mutation.ClearExcludedAmount()
	return cu
}

// SetTaxableAmount sets the "taxable_amount" field.
func (cu *CommissionUpdate) SetTaxableAmount(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetTaxableAmount()
	cu.mutation.SetTaxableAmount(d)
	return cu
}

// SetNillableTaxableAmount sets the "taxable_amount" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableTaxableAmount(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetTaxableAmount(*d)
	}
	return cu
}

// AddTaxableAmount adds d to the "taxable_amount" field.
func (cu *CommissionUpdate) AddTaxableAmount(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddTaxableAmount(d)
	return cu
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (cu *CommissionUpdate) ClearTaxableAmount() *CommissionUpdate {
	cu.mutation.ClearTaxableAmount()
	return cu
}

// SetRate sets the "rate" field.
func (cu *CommissionUpdate) SetRate(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetRate()
	cu.mutation.SetRate(d)
	return cu
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableRate(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetRate(*d)
	}
	return cu
}

// AddRate adds d to the "rate" field.
func (cu *CommissionUpdate) AddRate(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddRate(d)
	return cu
}

// ClearRate clears the value of the "rate" field.
func (cu *CommissionUpdate) ClearRate() *CommissionUpdate {
	cu.mutation.ClearRate()
	return cu
}

// SetCommission sets the "commission" field.
func (cu *CommissionUpdate) SetCommission(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetCommission()
	cu.mutation.SetCommission(d)
	return cu
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableCommission(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetCommission(*d)
	}
	return cu
}

// AddCommission adds d to the "commission" field.
func (cu *CommissionUpdate) AddCommission(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddCommission(d)
	return cu
}

// ClearCommission clears the value of the "commission" field.
func (cu *CommissionUpdate) ClearCommission() *CommissionUpdate {
	cu.mutation.ClearCommission()
	return cu
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (cu *CommissionUpdate) SetManagerShareRate(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetManagerShareRate()
	cu.mutation.SetManagerShareRate(d)
	return cu
}

// SetNillableManagerShareRate sets the "manager_share_rate" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableManagerShareRate(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetManagerShareRate(*d)
	}
	return cu
}

// AddManagerShareRate adds d to the "manager_share_rate" field.
func (cu *CommissionUpdate) AddManagerShareRate(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddManagerShareRate(d)
	return cu
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (cu *CommissionUpdate) ClearManagerShareRate() *CommissionUpdate {
	cu.mutation.ClearManagerShareRate()
	return cu
}

// SetManagerShare sets the "manager_share" field.
func (cu *CommissionUpdate) SetManagerShare(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.ResetManagerShare()
	cu.mutation.SetManagerShare(d)
	return cu
}

// SetNillableManagerShare sets the "manager_share" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableManagerShare(d *decimal.Decimal) *CommissionUpdate {
	if d != nil {
		cu.SetManagerShare(*d)
	}
	return cu
}

// AddManagerShare adds d to the "manager_share" field.
func (cu *CommissionUpdate) AddManagerShare(d decimal.Decimal) *CommissionUpdate {
	cu.mutation.AddManagerShare(d)
	return cu
}

// ClearManagerShare clears the value of the "manager_share" field.
func (cu *CommissionUpdate) ClearManagerShare() *CommissionUpdate {
	cu.mutation.ClearManagerShare()
	return cu
}

// SetStatus sets the "status" field.
func (cu *CommissionUpdate) SetStatus(es enum.CommissionStatus) *CommissionUpdate {
	cu.mutation.SetStatus(es)
	return cu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cu *CommissionUpdate) SetNillableStatus(es *enum.CommissionStatus) *CommissionUpdate {
	if es != nil {
		cu.SetStatus(*es)
	}
	return cu
}

// Mutation returns the CommissionMutation object of the builder.
func (cu *CommissionUpdate) Mutation() *CommissionMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CommissionUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CommissionUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CommissionUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CommissionUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := commission.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CommissionUpdate) check() error {
	if v, ok := cu.mutation.Status(); ok {
		if err := commission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Commission.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cu *CommissionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CommissionUpdate {
	cu.modifiers = append(cu.modifiers, modifiers...)
	return cu
}

func (cu *CommissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(commission.Table, commission.Columns, sqlgraph.NewFieldSpec(commission.FieldID, field.TypeInt64))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(commission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.PeriodStart(); ok {
		_spec.SetField(commission.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := cu.mutation.PeriodEnd(); ok {
		_spec.SetField(commission.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := cu.mutation.Gmv(); ok {
		_spec.SetField(commission.FieldGmv, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedGmv(); ok {
		_spec.AddField(commission.FieldGmv, field.TypeFloat64, value)
	}
	if cu.mutation.GmvCleared() {
		_spec.ClearField(commission.FieldGmv, field.TypeFloat64)
	}
	if value, ok := cu.mutation.ExcludedAmount(); ok {
		_spec.SetField(commission.FieldExcludedAmount, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedExcludedAmount(); ok {
		_spec.AddField(commission.FieldExcludedAmount, field.TypeFloat64, value)
	}
	if cu.mutation.ExcludedAmountCleared() {
		_spec.ClearField(commission.FieldExcludedAmount, field.TypeFloat64)
	}
	if value, ok := cu.mutation.TaxableAmount(); ok {
		_spec.SetField(commission.FieldTaxableAmount, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedTaxableAmount(); ok {
		_spec.AddField(commission.FieldTaxableAmount, field.TypeFloat64, value)
	}
	if cu.mutation.TaxableAmountCleared() {
		_spec.ClearField(commission.FieldTaxableAmount, field.TypeFloat64)
	}
	if value, ok := cu.mutation.Rate(); ok {
		_spec.SetField(commission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedRate(); ok {
		_spec.AddField(commission.FieldRate, field.TypeFloat64, value)
	}
	if cu.mutation.RateCleared() {
		_spec.ClearField(commission.FieldRate, field.TypeFloat64)
	}
	if value, ok := cu.mutation.Commission(); ok {
		_spec.SetField(commission.FieldCommission, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedCommission(); ok {
		_spec.AddField(commission.FieldCommission, field.TypeFloat64, value)
	}
	if cu.mutation.CommissionCleared() {
		_spec.ClearField(commission.FieldCommission, field.TypeFloat64)
	}
	if value, ok := cu.mutation.ManagerShareRate(); ok {
		_spec.SetField(commission.FieldManagerShareRate, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedManagerShareRate(); ok {
		_spec.AddField(commission.FieldManagerShareRate, field.TypeFloat64, value)
	}
	if cu.mutation.ManagerShareRateCleared() {
		_spec.ClearField(commission.FieldManagerShareRate, field.TypeFloat64)
	}
	if value, ok := cu.mutation.ManagerShare(); ok {
		_spec.SetField(commission.FieldManagerShare, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedManagerShare(); ok {
		_spec.AddField(commission.FieldManagerShare, field.TypeFloat64, value)
	}
	if cu.mutation.ManagerShareCleared() {
		_spec.ClearField(commission.FieldManagerShare, field.TypeFloat64)
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.SetField(commission.FieldStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(cu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CommissionUpdateOne is the builder for updating a single Commission entity.
type CommissionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CommissionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CommissionUpdateOne) SetUpdatedAt(t time.Time) *CommissionUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetPeriodStart sets the "period_start" field.
func (cuo *CommissionUpdateOne) SetPeriodStart(t time.Time) *CommissionUpdateOne {
	cuo.mutation.SetPeriodStart(t)
	return cuo
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillablePeriodStart(t *time.Time) *CommissionUpdateOne {
	if t != nil {
		cuo.SetPeriodStart(*t)
	}
	return cuo
}

// SetPeriodEnd sets the "period_end" field.
func (cuo *CommissionUpdateOne) SetPeriodEnd(t time.Time) *CommissionUpdateOne {
	cuo.mutation.SetPeriodEnd(t)
	return cuo
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillablePeriodEnd(t *time.Time) *CommissionUpdateOne {
	if t != nil {
		cuo.SetPeriodEnd(*t)
	}
	return cuo
}

// SetGmv sets the "gmv" field.
func (cuo *CommissionUpdateOne) SetGmv(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetGmv()
	cuo.mutation.SetGmv(d)
	return cuo
}

// SetNillableGmv sets the "gmv" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableGmv(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetGmv(*d)
	}
	return cuo
}

// AddGmv adds d to the "gmv" field.
func (cuo *CommissionUpdateOne) AddGmv(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddGmv(d)
	return cuo
}

// ClearGmv clears the value of the "gmv" field.
func (cuo *CommissionUpdateOne) ClearGmv() *CommissionUpdateOne {
	cuo.mutation.ClearGmv()
	return cuo
}

// SetExcludedAmount sets the "excluded_amount" field.
func (cuo *CommissionUpdateOne) SetExcludedAmount(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetExcludedAmount()
	cuo.mutation.SetExcludedAmount(d)
	return cuo
}

// SetNillableExcludedAmount sets the "excluded_amount" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableExcludedAmount(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetExcludedAmount(*d)
	}
	return cuo
}

// AddExcludedAmount adds d to the "excluded_amount" field.
func (cuo *CommissionUpdateOne) AddExcludedAmount(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddExcludedAmount(d)
	return cuo
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (cuo *CommissionUpdateOne) ClearExcludedAmount() *CommissionUpdateOne {
	cuo.mutation.ClearExcludedAmount()
	return cuo
}

// SetTaxableAmount sets the "taxable_amount" field.
func (cuo *CommissionUpdateOne) SetTaxableAmount(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetTaxableAmount()
	cuo.mutation.SetTaxableAmount(d)
	return cuo
}

// SetNillableTaxableAmount sets the "taxable_amount" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableTaxableAmount(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetTaxableAmount(*d)
	}
	return cuo
}

// AddTaxableAmount adds d to the "taxable_amount" field.
func (cuo *CommissionUpdateOne) AddTaxableAmount(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddTaxableAmount(d)
	return cuo
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (cuo *CommissionUpdateOne) ClearTaxableAmount() *CommissionUpdateOne {
	cuo.mutation.ClearTaxableAmount()
	return cuo
}

// SetRate sets the "rate" field.
func (cuo *CommissionUpdateOne) SetRate(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetRate()
	cuo.mutation.SetRate(d)
	return cuo
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableRate(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetRate(*d)
	}
	return cuo
}

// AddRate adds d to the "rate" field.
func (cuo *CommissionUpdateOne) AddRate(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddRate(d)
	return cuo
}

// ClearRate clears the value of the "rate" field.
func (cuo *CommissionUpdateOne) ClearRate() *CommissionUpdateOne {
	cuo.mutation.ClearRate()
	return cuo
}

// SetCommission sets the "commission" field.
func (cuo *CommissionUpdateOne) SetCommission(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetCommission()
	cuo.mutation.SetCommission(d)
	return cuo
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableCommission(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetCommission(*d)
	}
	return cuo
}

// AddCommission adds d to the "commission" field.
func (cuo *CommissionUpdateOne) AddCommission(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddCommission(d)
	return cuo
}

// ClearCommission clears the value of the "commission" field.
func (cuo *CommissionUpdateOne) ClearCommission() *CommissionUpdateOne {
	cuo.mutation.ClearCommission()
	return cuo
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (cuo *CommissionUpdateOne) SetManagerShareRate(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetManagerShareRate()
	cuo.mutation.SetManagerShareRate(d)
	return cuo
}

// SetNillableManagerShareRate sets the "manager_share_rate" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableManagerShareRate(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetManagerShareRate(*d)
	}
	return cuo
}

// AddManagerShareRate adds d to the "manager_share_rate" field.
func (cuo *CommissionUpdateOne) AddManagerShareRate(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddManagerShareRate(d)
	return cuo
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (cuo *CommissionUpdateOne) ClearManagerShareRate() *CommissionUpdateOne {
	cuo.mutation.ClearManagerShareRate()
	return cuo
}

// SetManagerShare sets the "manager_share" field.
func (cuo *CommissionUpdateOne) SetManagerShare(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.ResetManagerShare()
	cuo.mutation.SetManagerShare(d)
	return cuo
}

// SetNillableManagerShare sets the "manager_share" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableManagerShare(d *decimal.Decimal) *CommissionUpdateOne {
	if d != nil {
		cuo.SetManagerShare(*d)
	}
	return cuo
}

// AddManagerShare adds d to the "manager_share" field.
func (cuo *CommissionUpdateOne) AddManagerShare(d decimal.Decimal) *CommissionUpdateOne {
	cuo.mutation.AddManagerShare(d)
	return cuo
}

// ClearManagerShare clears the value of the "manager_share" field.
func (cuo *CommissionUpdateOne) ClearManagerShare() *CommissionUpdateOne {
	cuo.mutation.ClearManagerShare()
	return cuo
}

// SetStatus sets the "status" field.
func (cuo *CommissionUpdateOne) SetStatus(es enum.CommissionStatus) *CommissionUpdateOne {
	cuo.mutation.SetStatus(es)
	return cuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cuo *CommissionUpdateOne) SetNillableStatus(es *enum.CommissionStatus) *CommissionUpdateOne {
	if es != nil {
		cuo.SetStatus(*es)
	}
	return cuo
}

// Mutation returns the CommissionMutation object of the builder.
func (cuo *CommissionUpdateOne) Mutation() *CommissionMutation {
	return cuo.mutation
}

// Where appends a list predicates to the CommissionUpdate builder.
func (cuo *CommissionUpdateOne) Where(ps ...predicate.Commission) *CommissionUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CommissionUpdateOne) Select(field string, fields ...string) *CommissionUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Commission entity.
func (cuo *CommissionUpdateOne) Save(ctx context.Context) (*Commission, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CommissionUpdateOne) SaveX(ctx context.Context) *Commission {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CommissionUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CommissionUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := commission.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CommissionUpdateOne) check() error {
	if v, ok := cuo.mutation.Status(); ok {
		if err := commission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Commission.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (cuo *CommissionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CommissionUpdateOne {
	cuo.modifiers = append(cuo.modifiers, modifiers...)
	return cuo
}

func (cuo *CommissionUpdateOne) sqlSave(ctx context.Context) (_node *Commission, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(commission.Table, commission.Columns, sqlgraph.NewFieldSpec(commission.FieldID, field.TypeInt64))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Commission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, commission.FieldID)
		for _, f := range fields {
			if !commission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != commission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(commission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.PeriodStart(); ok {
		_spec.SetField(commission.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.PeriodEnd(); ok {
		_spec.SetField(commission.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.Gmv(); ok {
		_spec.SetField(commission.FieldGmv, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedGmv(); ok {
		_spec.AddField(commission.FieldGmv, field.TypeFloat64, value)
	}
	if cuo.mutation.GmvCleared() {
		_spec.ClearField(commission.FieldGmv, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.ExcludedAmount(); ok {
		_spec.SetField(commission.FieldExcludedAmount, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedExcludedAmount(); ok {
		_spec.AddField(commission.FieldExcludedAmount, field.TypeFloat64, value)
	}
	if cuo.mutation.ExcludedAmountCleared() {
		_spec.ClearField(commission.FieldExcludedAmount, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.TaxableAmount(); ok {
		_spec.SetField(commission.FieldTaxableAmount, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedTaxableAmount(); ok {
		_spec.AddField(commission.FieldTaxableAmount, field.TypeFloat64, value)
	}
	if cuo.mutation.TaxableAmountCleared() {
		_spec.ClearField(commission.FieldTaxableAmount, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.Rate(); ok {
		_spec.SetField(commission.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedRate(); ok {
		_spec.AddField(commission.FieldRate, field.TypeFloat64, value)
	}
	if cuo.mutation.RateCleared() {
		_spec.ClearField(commission.FieldRate, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.Commission(); ok {
		_spec.SetField(commission.FieldCommission, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedCommission(); ok {
		_spec.AddField(commission.FieldCommission, field.TypeFloat64, value)
	}
	if cuo.mutation.CommissionCleared() {
		_spec.ClearField(commission.FieldCommission, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.ManagerShareRate(); ok {
		_spec.SetField(commission.FieldManagerShareRate, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedManagerShareRate(); ok {
		_spec.AddField(commission.FieldManagerShareRate, field.TypeFloat64, value)
	}
	if cuo.mutation.ManagerShareRateCleared() {
		_spec.ClearField(commission.FieldManagerShareRate, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.ManagerShare(); ok {
		_spec.SetField(commission.FieldManagerShare, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedManagerShare(); ok {
		_spec.AddField(commission.FieldManagerShare, field.TypeFloat64, value)
	}
	if cuo.mutation.ManagerShareCleared() {
		_spec.ClearField(commission.FieldManagerShare, field.TypeFloat64)
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.SetField(commission.FieldStatus, field.TypeEnum, value)
	}
	_spec.AddModifiers(cuo.modifiers...)
	_node = &Commission{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{commission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
