// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/platform-billing/ent/commission"
	"github.com/makesalekz/platform-billing/ent/enum"
)

// Commission is the model entity for the Commission schema.
type Commission struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd time.Time `json:"period_end,omitempty"`
	// Gmv holds the value of the "gmv" field.
	Gmv decimal.Decimal `json:"gmv,omitempty"`
	// ExcludedAmount holds the value of the "excluded_amount" field.
	ExcludedAmount decimal.Decimal `json:"excluded_amount,omitempty"`
	// TaxableAmount holds the value of the "taxable_amount" field.
	TaxableAmount decimal.Decimal `json:"taxable_amount,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate decimal.Decimal `json:"rate,omitempty"`
	// Commission holds the value of the "commission" field.
	Commission decimal.Decimal `json:"commission,omitempty"`
	// ManagerShareRate holds the value of the "manager_share_rate" field.
	ManagerShareRate decimal.Decimal `json:"manager_share_rate,omitempty"`
	// ManagerShare holds the value of the "manager_share" field.
	ManagerShare decimal.Decimal `json:"manager_share,omitempty"`
	// Status holds the value of the "status" field.
	Status       enum.CommissionStatus `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Commission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case commission.FieldGmv, commission.FieldExcludedAmount, commission.FieldTaxableAmount, commission.FieldRate, commission.FieldCommission, commission.FieldManagerShareRate, commission.FieldManagerShare:
			values[i] = new(decimal.Decimal)
		case commission.FieldID, commission.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case commission.FieldStatus:
			values[i] = new(sql.NullString)
		case commission.FieldCreatedAt, commission.FieldUpdatedAt, commission.FieldPeriodStart, commission.FieldPeriodEnd:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Commission fields.
func (c *Commission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case commission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int64(value.Int64)
		case commission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case commission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		case commission.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				c.TenantID = value.Int64
			}
		case commission.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				c.PeriodStart = value.Time
			}
		case commission.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				c.PeriodEnd = value.Time
			}
		case commission.FieldGmv:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field gmv", values[i])
			} else if value != nil {
				c.Gmv = *value
			}
		case commission.FieldExcludedAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field excluded_amount", values[i])
			} else if value != nil {
				c.ExcludedAmount = *value
			}
		case commission.FieldTaxableAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field taxable_amount", values[i])
			} else if value != nil {
				c.TaxableAmount = *value
			}
		case commission.FieldRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value != nil {
				c.Rate = *value
			}
		case commission.FieldCommission:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field commission", values[i])
			} else if value != nil {
				c.Commission = *value
			}
		case commission.FieldManagerShareRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field manager_share_rate", values[i])
			} else if value != nil {
				c.ManagerShareRate = *value
			}
		case commission.FieldManagerShare:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field manager_share", values[i])
			} else if value != nil {
				c.ManagerShare = *value
			}
		case commission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				c.Status = enum.CommissionStatus(value.String)
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Commission.
// This includes values selected through modifiers, order, etc.
func (c *Commission) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Commission.
// Note that you need to call Commission.Unwrap() before calling this method if this Commission
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Commission) Update() *CommissionUpdateOne {
	return NewCommissionClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Commission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Commission) Unwrap() *Commission {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Commission is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Commission) String() string {
	var builder strings.Builder
	builder.WriteString("Commission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", c.TenantID))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(c.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_end=")
	builder.WriteString(c.PeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("gmv=")
	builder.WriteString(fmt.Sprintf("%v", c.Gmv))
	builder.WriteString(", ")
	builder.WriteString("excluded_amount=")
	builder.WriteString(fmt.Sprintf("%v", c.ExcludedAmount))
	builder.WriteString(", ")
	builder.WriteString("taxable_amount=")
	builder.WriteString(fmt.Sprintf("%v", c.TaxableAmount))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", c.Rate))
	builder.WriteString(", ")
	builder.WriteString("commission=")
	builder.WriteString(fmt.Sprintf("%v", c.Commission))
	builder.WriteString(", ")
	builder.WriteString("manager_share_rate=")
	builder.WriteString(fmt.Sprintf("%v", c.ManagerShareRate))
	builder.WriteString(", ")
	builder.WriteString("manager_share=")
	builder.WriteString(fmt.Sprintf("%v", c.ManagerShare))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", c.Status))
	builder.WriteByte(')')
	return builder.String()
}

// Commissions is a parsable slice of Commission.
type Commissions []*Commission
