// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/platform-billing/ent/commission"
	"github.com/makesalekz/platform-billing/ent/enum"
)

// CommissionCreate is the builder for creating a Commission entity.
type CommissionCreate struct {
	config
	mutation *CommissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cc *CommissionCreate) SetCreatedAt(t time.Time) *CommissionCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableCreatedAt(t *time.Time) *CommissionCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *CommissionCreate) SetUpdatedAt(t time.Time) *CommissionCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableUpdatedAt(t *time.Time) *CommissionCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetTenantID sets the "tenant_id" field.
func (cc *CommissionCreate) SetTenantID(i int64) *CommissionCreate {
	cc.mutation.SetTenantID(i)
	return cc
}

// SetPeriodStart sets the "period_start" field.
func (cc *CommissionCreate) SetPeriodStart(t time.Time) *CommissionCreate {
	cc.mutation.SetPeriodStart(t)
	return cc
}

// SetPeriodEnd sets the "period_end" field.
func (cc *CommissionCreate) SetPeriodEnd(t time.Time) *CommissionCreate {
	cc.mutation.SetPeriodEnd(t)
	return cc
}

// SetGmv sets the "gmv" field.
func (cc *CommissionCreate) SetGmv(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetGmv(d)
	return cc
}

// SetNillableGmv sets the "gmv" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableGmv(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetGmv(*d)
	}
	return cc
}

// SetExcludedAmount sets the "excluded_amount" field.
func (cc *CommissionCreate) SetExcludedAmount(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetExcludedAmount(d)
	return cc
}

// SetNillableExcludedAmount sets the "excluded_amount" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableExcludedAmount(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetExcludedAmount(*d)
	}
	return cc
}

// SetTaxableAmount sets the "taxable_amount" field.
func (cc *CommissionCreate) SetTaxableAmount(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetTaxableAmount(d)
	return cc
}

// SetNillableTaxableAmount sets the "taxable_amount" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableTaxableAmount(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetTaxableAmount(*d)
	}
	return cc
}

// SetRate sets the "rate" field.
func (cc *CommissionCreate) SetRate(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetRate(d)
	return cc
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableRate(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetRate(*d)
	}
	return cc
}

// SetCommission sets the "commission" field.
func (cc *CommissionCreate) SetCommission(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetCommission(d)
	return cc
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableCommission(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetCommission(*d)
	}
	return cc
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (cc *CommissionCreate) SetManagerShareRate(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetManagerShareRate(d)
	return cc
}

// SetNillableManagerShareRate sets the "manager_share_rate" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableManagerShareRate(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetManagerShareRate(*d)
	}
	return cc
}

// SetManagerShare sets the "manager_share" field.
func (cc *CommissionCreate) SetManagerShare(d decimal.Decimal) *CommissionCreate {
	cc.mutation.SetManagerShare(d)
	return cc
}

// SetNillableManagerShare sets the "manager_share" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableManagerShare(d *decimal.Decimal) *CommissionCreate {
	if d != nil {
		cc.SetManagerShare(*d)
	}
	return cc
}

// SetStatus sets the "status" field.
func (cc *CommissionCreate) SetStatus(es enum.CommissionStatus) *CommissionCreate {
	cc.mutation.SetStatus(es)
	return cc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cc *CommissionCreate) SetNillableStatus(es *enum.CommissionStatus) *CommissionCreate {
	if es != nil {
		cc.SetStatus(*es)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CommissionCreate) SetID(i int64) *CommissionCreate {
	cc.mutation.SetID(i)
	return cc
}

// Mutation returns the CommissionMutation object of the builder.
func (cc *CommissionCreate) Mutation() *CommissionMutation {
	return cc.mutation
}

// Save creates the Commission in the database.
func (cc *CommissionCreate) Save(ctx context.Context) (*Commission, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommissionCreate) SaveX(ctx context.Context) *Commission {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommissionCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommissionCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CommissionCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := commission.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := commission.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.Status(); !ok {
		v := commission.DefaultStatus
		cc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommissionCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Commission.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Commission.updated_at"`)}
	}
	if _, ok := cc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Commission.tenant_id"`)}
	}
	if _, ok := cc.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "Commission.period_start"`)}
	}
	if _, ok := cc.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "Commission.period_end"`)}
	}
	if _, ok := cc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Commission.status"`)}
	}
	if v, ok := cc.mutation.Status(); ok {
		if err := commission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Commission.status": %w`, err)}
		}
	}
	return nil
}

func (cc *CommissionCreate) sqlSave(ctx context.Context) (*Commission, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommissionCreate) createSpec() (*Commission, *sqlgraph.CreateSpec) {
	var (
		_node = &Commission{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(commission.Table, sqlgraph.NewFieldSpec(commission.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = cc.conflict
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(commission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(commission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.TenantID(); ok {
		_spec.SetField(commission.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := cc.mutation.PeriodStart(); ok {
		_spec.SetField(commission.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := cc.mutation.PeriodEnd(); ok {
		_spec.SetField(commission.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := cc.mutation.Gmv(); ok {
		_spec.SetField(commission.FieldGmv, field.TypeFloat64, value)
		_node.Gmv = value
	}
	if value, ok := cc.mutation.ExcludedAmount(); ok {
		_spec.SetField(commission.FieldExcludedAmount, field.TypeFloat64, value)
		_node.ExcludedAmount = value
	}
	if value, ok := cc.mutation.TaxableAmount(); ok {
		_spec.SetField(commission.FieldTaxableAmount, field.TypeFloat64, value)
		_node.TaxableAmount = value
	}
	if value, ok := cc.mutation.Rate(); ok {
		_spec.SetField(commission.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := cc.mutation.Commission(); ok {
		_spec.SetField(commission.FieldCommission, field.TypeFloat64, value)
		_node.Commission = value
	}
	if value, ok := cc.mutation.ManagerShareRate(); ok {
		_spec.SetField(commission.FieldManagerShareRate, field.TypeFloat64, value)
		_node.ManagerShareRate = value
	}
	if value, ok := cc.mutation.ManagerShare(); ok {
		_spec.SetField(commission.FieldManagerShare, field.TypeFloat64, value)
		_node.ManagerShare = value
	}
	if value, ok := cc.mutation.Status(); ok {
		_spec.SetField(commission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Commission.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (cc *CommissionCreate) OnConflict(opts ...sql.ConflictOption) *CommissionUpsertOne {
	cc.conflict = opts
	return &CommissionUpsertOne{
		create: cc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Commission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cc *CommissionCreate) OnConflictColumns(columns ...string) *CommissionUpsertOne {
	cc.conflict = append(cc.conflict, sql.ConflictColumns(columns...))
	return &CommissionUpsertOne{
		create: cc,
	}
}

type (
	// CommissionUpsertOne is the builder for "upsert"-ing
	//  one Commission node.
	CommissionUpsertOne struct {
		create *CommissionCreate
	}

	// CommissionUpsert is the "OnConflict" setter.
	CommissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionUpsert) SetUpdatedAt(v time.Time) *CommissionUpsert {
	u.Set(commission.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateUpdatedAt() *CommissionUpsert {
	u.SetExcluded(commission.FieldUpdatedAt)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *CommissionUpsert) SetPeriodStart(v time.Time) *CommissionUpsert {
	u.Set(commission.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *CommissionUpsert) UpdatePeriodStart() *CommissionUpsert {
	u.SetExcluded(commission.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *CommissionUpsert) SetPeriodEnd(v time.Time) *CommissionUpsert {
	u.Set(commission.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *CommissionUpsert) UpdatePeriodEnd() *CommissionUpsert {
	u.SetExcluded(commission.FieldPeriodEnd)
	return u
}

// SetGmv sets the "gmv" field.
func (u *CommissionUpsert) SetGmv(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldGmv, v)
	return u
}

// UpdateGmv sets the "gmv" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateGmv() *CommissionUpsert {
	u.SetExcluded(commission.FieldGmv)
	return u
}

// AddGmv adds v to the "gmv" field.
func (u *CommissionUpsert) AddGmv(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldGmv, v)
	return u
}

// ClearGmv clears the value of the "gmv" field.
func (u *CommissionUpsert) ClearGmv() *CommissionUpsert {
	u.SetNull(commission.FieldGmv)
	return u
}

// SetExcludedAmount sets the "excluded_amount" field.
func (u *CommissionUpsert) SetExcludedAmount(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldExcludedAmount, v)
	return u
}

// UpdateExcludedAmount sets the "excluded_amount" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateExcludedAmount() *CommissionUpsert {
	u.SetExcluded(commission.FieldExcludedAmount)
	return u
}

// AddExcludedAmount adds v to the "excluded_amount" field.
func (u *CommissionUpsert) AddExcludedAmount(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldExcludedAmount, v)
	return u
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (u *CommissionUpsert) ClearExcludedAmount() *CommissionUpsert {
	u.SetNull(commission.FieldExcludedAmount)
	return u
}

// SetTaxableAmount sets the "taxable_amount" field.
func (u *CommissionUpsert) SetTaxableAmount(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldTaxableAmount, v)
	return u
}

// UpdateTaxableAmount sets the "taxable_amount" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateTaxableAmount() *CommissionUpsert {
	u.SetExcluded(commission.FieldTaxableAmount)
	return u
}

// AddTaxableAmount adds v to the "taxable_amount" field.
func (u *CommissionUpsert) AddTaxableAmount(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldTaxableAmount, v)
	return u
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (u *CommissionUpsert) ClearTaxableAmount() *CommissionUpsert {
	u.SetNull(commission.FieldTaxableAmount)
	return u
}

// SetRate sets the "rate" field.
func (u *CommissionUpsert) SetRate(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateRate() *CommissionUpsert {
	u.SetExcluded(commission.FieldRate)
	return u
}

// AddRate adds v to the "rate" field.
func (u *CommissionUpsert) AddRate(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldRate, v)
	return u
}

// ClearRate clears the value of the "rate" field.
func (u *CommissionUpsert) ClearRate() *CommissionUpsert {
	u.SetNull(commission.FieldRate)
	return u
}

// SetCommission sets the "commission" field.
func (u *CommissionUpsert) SetCommission(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldCommission, v)
	return u
}

// UpdateCommission sets the "commission" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateCommission() *CommissionUpsert {
	u.SetExcluded(commission.FieldCommission)
	return u
}

// AddCommission adds v to the "commission" field.
func (u *CommissionUpsert) AddCommission(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldCommission, v)
	return u
}

// ClearCommission clears the value of the "commission" field.
func (u *CommissionUpsert) ClearCommission() *CommissionUpsert {
	u.SetNull(commission.FieldCommission)
	return u
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (u *CommissionUpsert) SetManagerShareRate(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldManagerShareRate, v)
	return u
}

// UpdateManagerShareRate sets the "manager_share_rate" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateManagerShareRate() *CommissionUpsert {
	u.SetExcluded(commission.FieldManagerShareRate)
	return u
}

// AddManagerShareRate adds v to the "manager_share_rate" field.
func (u *CommissionUpsert) AddManagerShareRate(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldManagerShareRate, v)
	return u
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (u *CommissionUpsert) ClearManagerShareRate() *CommissionUpsert {
	u.SetNull(commission.FieldManagerShareRate)
	return u
}

// SetManagerShare sets the "manager_share" field.
func (u *CommissionUpsert) SetManagerShare(v decimal.Decimal) *CommissionUpsert {
	u.Set(commission.FieldManagerShare, v)
	return u
}

// UpdateManagerShare sets the "manager_share" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateManagerShare() *CommissionUpsert {
	u.SetExcluded(commission.FieldManagerShare)
	return u
}

// AddManagerShare adds v to the "manager_share" field.
func (u *CommissionUpsert) AddManagerShare(v decimal.Decimal) *CommissionUpsert {
	u.Add(commission.FieldManagerShare, v)
	return u
}

// ClearManagerShare clears the value of the "manager_share" field.
func (u *CommissionUpsert) ClearManagerShare() *CommissionUpsert {
	u.SetNull(commission.FieldManagerShare)
	return u
}

// SetStatus sets the "status" field.
func (u *CommissionUpsert) SetStatus(v enum.CommissionStatus) *CommissionUpsert {
	u.Set(commission.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionUpsert) UpdateStatus() *CommissionUpsert {
	u.SetExcluded(commission.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Commission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(commission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommissionUpsertOne) UpdateNewValues() *CommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(commission.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(commission.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(commission.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Commission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommissionUpsertOne) Ignore() *CommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionUpsertOne) DoNothing() *CommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionCreate.OnConflict
// documentation for more info.
func (u *CommissionUpsertOne) Update(set func(*CommissionUpsert)) *CommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionUpsertOne) SetUpdatedAt(v time.Time) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateUpdatedAt() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *CommissionUpsertOne) SetPeriodStart(v time.Time) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdatePeriodStart() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *CommissionUpsertOne) SetPeriodEnd(v time.Time) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdatePeriodEnd() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetGmv sets the "gmv" field.
func (u *CommissionUpsertOne) SetGmv(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetGmv(v)
	})
}

// AddGmv adds v to the "gmv" field.
func (u *CommissionUpsertOne) AddGmv(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddGmv(v)
	})
}

// UpdateGmv sets the "gmv" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateGmv() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateGmv()
	})
}

// ClearGmv clears the value of the "gmv" field.
func (u *CommissionUpsertOne) ClearGmv() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearGmv()
	})
}

// SetExcludedAmount sets the "excluded_amount" field.
func (u *CommissionUpsertOne) SetExcludedAmount(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetExcludedAmount(v)
	})
}

// AddExcludedAmount adds v to the "excluded_amount" field.
func (u *CommissionUpsertOne) AddExcludedAmount(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddExcludedAmount(v)
	})
}

// UpdateExcludedAmount sets the "excluded_amount" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateExcludedAmount() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateExcludedAmount()
	})
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (u *CommissionUpsertOne) ClearExcludedAmount() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearExcludedAmount()
	})
}

// SetTaxableAmount sets the "taxable_amount" field.
func (u *CommissionUpsertOne) SetTaxableAmount(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetTaxableAmount(v)
	})
}

// AddTaxableAmount adds v to the "taxable_amount" field.
func (u *CommissionUpsertOne) AddTaxableAmount(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddTaxableAmount(v)
	})
}

// UpdateTaxableAmount sets the "taxable_amount" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateTaxableAmount() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateTaxableAmount()
	})
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (u *CommissionUpsertOne) ClearTaxableAmount() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearTaxableAmount()
	})
}

// SetRate sets the "rate" field.
func (u *CommissionUpsertOne) SetRate(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *CommissionUpsertOne) AddRate(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateRate() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateRate()
	})
}

// ClearRate clears the value of the "rate" field.
func (u *CommissionUpsertOne) ClearRate() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearRate()
	})
}

// SetCommission sets the "commission" field.
func (u *CommissionUpsertOne) SetCommission(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetCommission(v)
	})
}

// AddCommission adds v to the "commission" field.
func (u *CommissionUpsertOne) AddCommission(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddCommission(v)
	})
}

// UpdateCommission sets the "commission" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateCommission() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateCommission()
	})
}

// ClearCommission clears the value of the "commission" field.
func (u *CommissionUpsertOne) ClearCommission() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearCommission()
	})
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (u *CommissionUpsertOne) SetManagerShareRate(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetManagerShareRate(v)
	})
}

// AddManagerShareRate adds v to the "manager_share_rate" field.
func (u *CommissionUpsertOne) AddManagerShareRate(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddManagerShareRate(v)
	})
}

// UpdateManagerShareRate sets the "manager_share_rate" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateManagerShareRate() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateManagerShareRate()
	})
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (u *CommissionUpsertOne) ClearManagerShareRate() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearManagerShareRate()
	})
}

// SetManagerShare sets the "manager_share" field.
func (u *CommissionUpsertOne) SetManagerShare(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetManagerShare(v)
	})
}

// AddManagerShare adds v to the "manager_share" field.
func (u *CommissionUpsertOne) AddManagerShare(v decimal.Decimal) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.AddManagerShare(v)
	})
}

// UpdateManagerShare sets the "manager_share" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateManagerShare() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateManagerShare()
	})
}

// ClearManagerShare clears the value of the "manager_share" field.
func (u *CommissionUpsertOne) ClearManagerShare() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearManagerShare()
	})
}

// SetStatus sets the "status" field.
func (u *CommissionUpsertOne) SetStatus(v enum.CommissionStatus) *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionUpsertOne) UpdateStatus() *CommissionUpsertOne {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CommissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommissionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommissionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommissionCreateBulk is the builder for creating many Commission entities in bulk.
type CommissionCreateBulk struct {
	config
	err      error
	builders []*CommissionCreate
	conflict []sql.ConflictOption
}

// Save creates the Commission entities in the database.
func (ccb *CommissionCreateBulk) Save(ctx context.Context) ([]*Commission, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Commission, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommissionCreateBulk) SaveX(ctx context.Context) []*Commission {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommissionCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommissionCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Commission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommissionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ccb *CommissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommissionUpsertBulk {
	ccb.conflict = opts
	return &CommissionUpsertBulk{
		create: ccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Commission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ccb *CommissionCreateBulk) OnConflictColumns(columns ...string) *CommissionUpsertBulk {
	ccb.conflict = append(ccb.conflict, sql.ConflictColumns(columns...))
	return &CommissionUpsertBulk{
		create: ccb,
	}
}

// CommissionUpsertBulk is the builder for "upsert"-ing
// a bulk of Commission nodes.
type CommissionUpsertBulk struct {
	create *CommissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Commission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(commission.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommissionUpsertBulk) UpdateNewValues() *CommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(commission.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(commission.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(commission.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Commission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommissionUpsertBulk) Ignore() *CommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommissionUpsertBulk) DoNothing() *CommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommissionCreateBulk.OnConflict
// documentation for more info.
func (u *CommissionUpsertBulk) Update(set func(*CommissionUpsert)) *CommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CommissionUpsertBulk) SetUpdatedAt(v time.Time) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateUpdatedAt() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *CommissionUpsertBulk) SetPeriodStart(v time.Time) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdatePeriodStart() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *CommissionUpsertBulk) SetPeriodEnd(v time.Time) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdatePeriodEnd() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetGmv sets the "gmv" field.
func (u *CommissionUpsertBulk) SetGmv(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetGmv(v)
	})
}

// AddGmv adds v to the "gmv" field.
func (u *CommissionUpsertBulk) AddGmv(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddGmv(v)
	})
}

// UpdateGmv sets the "gmv" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateGmv() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateGmv()
	})
}

// ClearGmv clears the value of the "gmv" field.
func (u *CommissionUpsertBulk) ClearGmv() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearGmv()
	})
}

// SetExcludedAmount sets the "excluded_amount" field.
func (u *CommissionUpsertBulk) SetExcludedAmount(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetExcludedAmount(v)
	})
}

// AddExcludedAmount adds v to the "excluded_amount" field.
func (u *CommissionUpsertBulk) AddExcludedAmount(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddExcludedAmount(v)
	})
}

// UpdateExcludedAmount sets the "excluded_amount" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateExcludedAmount() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateExcludedAmount()
	})
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (u *CommissionUpsertBulk) ClearExcludedAmount() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearExcludedAmount()
	})
}

// SetTaxableAmount sets the "taxable_amount" field.
func (u *CommissionUpsertBulk) SetTaxableAmount(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetTaxableAmount(v)
	})
}

// AddTaxableAmount adds v to the "taxable_amount" field.
func (u *CommissionUpsertBulk) AddTaxableAmount(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddTaxableAmount(v)
	})
}

// UpdateTaxableAmount sets the "taxable_amount" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateTaxableAmount() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateTaxableAmount()
	})
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (u *CommissionUpsertBulk) ClearTaxableAmount() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearTaxableAmount()
	})
}

// SetRate sets the "rate" field.
func (u *CommissionUpsertBulk) SetRate(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetRate(v)
	})
}

// AddRate adds v to the "rate" field.
func (u *CommissionUpsertBulk) AddRate(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateRate() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateRate()
	})
}

// ClearRate clears the value of the "rate" field.
func (u *CommissionUpsertBulk) ClearRate() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearRate()
	})
}

// SetCommission sets the "commission" field.
func (u *CommissionUpsertBulk) SetCommission(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetCommission(v)
	})
}

// AddCommission adds v to the "commission" field.
func (u *CommissionUpsertBulk) AddCommission(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddCommission(v)
	})
}

// UpdateCommission sets the "commission" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateCommission() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateCommission()
	})
}

// ClearCommission clears the value of the "commission" field.
func (u *CommissionUpsertBulk) ClearCommission() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearCommission()
	})
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (u *CommissionUpsertBulk) SetManagerShareRate(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetManagerShareRate(v)
	})
}

// AddManagerShareRate adds v to the "manager_share_rate" field.
func (u *CommissionUpsertBulk) AddManagerShareRate(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddManagerShareRate(v)
	})
}

// UpdateManagerShareRate sets the "manager_share_rate" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateManagerShareRate() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateManagerShareRate()
	})
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (u *CommissionUpsertBulk) ClearManagerShareRate() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearManagerShareRate()
	})
}

// SetManagerShare sets the "manager_share" field.
func (u *CommissionUpsertBulk) SetManagerShare(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetManagerShare(v)
	})
}

// AddManagerShare adds v to the "manager_share" field.
func (u *CommissionUpsertBulk) AddManagerShare(v decimal.Decimal) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.AddManagerShare(v)
	})
}

// UpdateManagerShare sets the "manager_share" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateManagerShare() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateManagerShare()
	})
}

// ClearManagerShare clears the value of the "manager_share" field.
func (u *CommissionUpsertBulk) ClearManagerShare() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.ClearManagerShare()
	})
}

// SetStatus sets the "status" field.
func (u *CommissionUpsertBulk) SetStatus(v enum.CommissionStatus) *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CommissionUpsertBulk) UpdateStatus() *CommissionUpsertBulk {
	return u.Update(func(s *CommissionUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *CommissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
