// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/platform-billing/ent/exclusion"
	"github.com/makesalekz/platform-billing/ent/predicate"
)

// ExclusionUpdate is the builder for updating Exclusion entities.
type ExclusionUpdate struct {
	config
	hooks     []Hook
	mutation  *ExclusionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ExclusionUpdate builder.
func (eu *ExclusionUpdate) Where(ps ...predicate.Exclusion) *ExclusionUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *ExclusionUpdate) SetUpdatedAt(t time.Time) *ExclusionUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetBrandName sets the "brand_name" field.
func (eu *ExclusionUpdate) SetBrandName(s string) *ExclusionUpdate {
	eu.mutation.SetBrandName(s)
	return eu
}

// SetNillableBrandName sets the "brand_name" field if the given value is not nil.
func (eu *ExclusionUpdate) SetNillableBrandName(s *string) *ExclusionUpdate {
	if s != nil {
		eu.SetBrandName(*s)
	}
	return eu
}

// SetSkuIds sets the "sku_ids" field.
func (eu *ExclusionUpdate) SetSkuIds(i []int64) *ExclusionUpdate {
	eu.mutation.SetSkuIds(i)
	return eu
}

// AppendSkuIds appends i to the "sku_ids" field.
func (eu *ExclusionUpdate) AppendSkuIds(i []int64) *ExclusionUpdate {
	eu.mutation.AppendSkuIds(i)
	return eu
}

// SetStartDate sets the "start_date" field.
func (eu *ExclusionUpdate) SetStartDate(t time.Time) *ExclusionUpdate {
	eu.mutation.SetStartDate(t)
	return eu
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (eu *ExclusionUpdate) SetNillableStartDate(t *time.Time) *ExclusionUpdate {
	if t != nil {
		eu.SetStartDate(*t)
	}
	return eu
}

// SetEndDate sets the "end_date" field.
func (eu *ExclusionUpdate) SetEndDate(t time.Time) *ExclusionUpdate {
	eu.mutation.SetEndDate(t)
	return eu
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (eu *ExclusionUpdate) SetNillableEndDate(t *time.Time) *ExclusionUpdate {
	if t != nil {
		eu.SetEndDate(*t)
	}
	return eu
}

// SetCreatedBy sets the "created_by" field.
func (eu *ExclusionUpdate) SetCreatedBy(i int64) *ExclusionUpdate {
	eu.mutation.ResetCreatedBy()
	eu.mutation.SetCreatedBy(i)
	return eu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (eu *ExclusionUpdate) SetNillableCreatedBy(i *int64) *ExclusionUpdate {
	if i != nil {
		eu.SetCreatedBy(*i)
	}
	return eu
}

// AddCreatedBy adds i to the "created_by" field.
func (eu *ExclusionUpdate) AddCreatedBy(i int64) *ExclusionUpdate {
	eu.mutation.AddCreatedBy(i)
	return eu
}

// Mutation returns the ExclusionMutation object of the builder.
func (eu *ExclusionUpdate) Mutation() *ExclusionMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *ExclusionUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExclusionUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExclusionUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExclusionUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *ExclusionUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := exclusion.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *ExclusionUpdate) check() error {
	if v, ok := eu.mutation.BrandName(); ok {
		if err := exclusion.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "Exclusion.brand_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (eu *ExclusionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExclusionUpdate {
	eu.modifiers = append(eu.modifiers, modifiers...)
	return eu
}

func (eu *ExclusionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(exclusion.Table, exclusion.Columns, sqlgraph.NewFieldSpec(exclusion.FieldID, field.TypeInt64))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(exclusion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.BrandName(); ok {
		_spec.SetField(exclusion.FieldBrandName, field.TypeString, value)
	}
	if value, ok := eu.mutation.SkuIds(); ok {
		_spec.SetField(exclusion.FieldSkuIds, field.TypeJSON, value)
	}
	if value, ok := eu.mutation.AppendedSkuIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, exclusion.FieldSkuIds, value)
		})
	}
	if value, ok := eu.mutation.StartDate(); ok {
		_spec.SetField(exclusion.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := eu.mutation.EndDate(); ok {
		_spec.SetField(exclusion.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := eu.mutation.CreatedBy(); ok {
		_spec.SetField(exclusion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := eu.mutation.AddedCreatedBy(); ok {
		_spec.AddField(exclusion.FieldCreatedBy, field.TypeInt64, value)
	}
	_spec.AddModifiers(eu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exclusion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// ExclusionUpdateOne is the builder for updating a single Exclusion entity.
type ExclusionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ExclusionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *ExclusionUpdateOne) SetUpdatedAt(t time.Time) *ExclusionUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetBrandName sets the "brand_name" field.
func (euo *ExclusionUpdateOne) SetBrandName(s string) *ExclusionUpdateOne {
	euo.mutation.SetBrandName(s)
	return euo
}

// SetNillableBrandName sets the "brand_name" field if the given value is not nil.
func (euo *ExclusionUpdateOne) SetNillableBrandName(s *string) *ExclusionUpdateOne {
	if s != nil {
		euo.SetBrandName(*s)
	}
	return euo
}

// SetSkuIds sets the "sku_ids" field.
func (euo *ExclusionUpdateOne) SetSkuIds(i []int64) *ExclusionUpdateOne {
	euo.mutation.SetSkuIds(i)
	return euo
}

// AppendSkuIds appends i to the "sku_ids" field.
func (euo *ExclusionUpdateOne) AppendSkuIds(i []int64) *ExclusionUpdateOne {
	euo.mutation.AppendSkuIds(i)
	return euo
}

// SetStartDate sets the "start_date" field.
func (euo *ExclusionUpdateOne) SetStartDate(t time.Time) *ExclusionUpdateOne {
	euo.mutation.SetStartDate(t)
	return euo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (euo *ExclusionUpdateOne) SetNillableStartDate(t *time.Time) *ExclusionUpdateOne {
	if t != nil {
		euo.SetStartDate(*t)
	}
	return euo
}

// SetEndDate sets the "end_date" field.
func (euo *ExclusionUpdateOne) SetEndDate(t time.Time) *ExclusionUpdateOne {
	euo.mutation.SetEndDate(t)
	return euo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (euo *ExclusionUpdateOne) SetNillableEndDate(t *time.Time) *ExclusionUpdateOne {
	if t != nil {
		euo.SetEndDate(*t)
	}
	return euo
}

// SetCreatedBy sets the "created_by" field.
func (euo *ExclusionUpdateOne) SetCreatedBy(i int64) *ExclusionUpdateOne {
	euo.mutation.ResetCreatedBy()
	euo.mutation.SetCreatedBy(i)
	return euo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (euo *ExclusionUpdateOne) SetNillableCreatedBy(i *int64) *ExclusionUpdateOne {
	if i != nil {
		euo.SetCreatedBy(*i)
	}
	return euo
}

// AddCreatedBy adds i to the "created_by" field.
func (euo *ExclusionUpdateOne) AddCreatedBy(i int64) *ExclusionUpdateOne {
	euo.mutation.AddCreatedBy(i)
	return euo
}

// Mutation returns the ExclusionMutation object of the builder.
func (euo *ExclusionUpdateOne) Mutation() *ExclusionMutation {
	return euo.mutation
}

// Where appends a list predicates to the ExclusionUpdate builder.
func (euo *ExclusionUpdateOne) Where(ps ...predicate.Exclusion) *ExclusionUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *ExclusionUpdateOne) Select(field string, fields ...string) *ExclusionUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Exclusion entity.
func (euo *ExclusionUpdateOne) Save(ctx context.Context) (*Exclusion, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExclusionUpdateOne) SaveX(ctx context.Context) *Exclusion {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *ExclusionUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExclusionUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *ExclusionUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := exclusion.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *ExclusionUpdateOne) check() error {
	if v, ok := euo.mutation.BrandName(); ok {
		if err := exclusion.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "Exclusion.brand_name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (euo *ExclusionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ExclusionUpdateOne {
	euo.modifiers = append(euo.modifiers, modifiers...)
	return euo
}

func (euo *ExclusionUpdateOne) sqlSave(ctx context.Context) (_node *Exclusion, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exclusion.Table, exclusion.Columns, sqlgraph.NewFieldSpec(exclusion.FieldID, field.TypeInt64))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Exclusion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exclusion.FieldID)
		for _, f := range fields {
			if !exclusion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exclusion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(exclusion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.BrandName(); ok {
		_spec.SetField(exclusion.FieldBrandName, field.TypeString, value)
	}
	if value, ok := euo.mutation.SkuIds(); ok {
		_spec.SetField(exclusion.FieldSkuIds, field.TypeJSON, value)
	}
	if value, ok := euo.mutation.AppendedSkuIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, exclusion.FieldSkuIds, value)
		})
	}
	if value, ok := euo.mutation.StartDate(); ok {
		_spec.SetField(exclusion.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := euo.mutation.EndDate(); ok {
		_spec.SetField(exclusion.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := euo.mutation.CreatedBy(); ok {
		_spec.SetField(exclusion.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := euo.mutation.AddedCreatedBy(); ok {
		_spec.AddField(exclusion.FieldCreatedBy, field.TypeInt64, value)
	}
	_spec.AddModifiers(euo.modifiers...)
	_node = &Exclusion{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exclusion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
