// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/platform-billing/ent/exclusion"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
)

// ExclusionDelete is the builder for deleting a Exclusion entity.
type ExclusionDelete struct {
	config
	hooks    []Hook
	mutation *ExclusionMutation
}

// Where appends a list predicates to the ExclusionDelete builder.
func (ed *ExclusionDelete) Where(ps ...predicate.Exclusion) *ExclusionDelete {
	ed.mutation.Where(ps...)
	return ed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ed *ExclusionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ed.sqlExec, ed.mutation, ed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ed *ExclusionDelete) ExecX(ctx context.Context) int {
	n, err := ed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ed *ExclusionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(exclusion.Table, sqlgraph.NewFieldSpec(exclusion.FieldID, field.TypeInt64))
	if ps := ed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ed.mutation.done = true
	return affected, err
}

// ExclusionDeleteOne is the builder for deleting a single Exclusion entity.
type ExclusionDeleteOne struct {
	ed *ExclusionDelete
}

// Where appends a list predicates to the ExclusionDelete builder.
func (edo *ExclusionDeleteOne) Where(ps ...predicate.Exclusion) *ExclusionDeleteOne {
	edo.ed.mutation.Where(ps...)
	return edo
}

// Exec executes the deletion query.
func (edo *ExclusionDeleteOne) Exec(ctx context.Context) error {
	n, err := edo.ed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{exclusion.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (edo *ExclusionDeleteOne) ExecX(ctx context.Context) {
	if err := edo.Exec(ctx); err != nil {
		panic(err)
	}
}
