// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/platform-billing/ent/exclusion"
)

// ExclusionCreate is the builder for creating a Exclusion entity.
type ExclusionCreate struct {
	config
	mutation *ExclusionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ec *ExclusionCreate) SetCreatedAt(t time.Time) *ExclusionCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *ExclusionCreate) SetNillableCreatedAt(t *time.Time) *ExclusionCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetUpdatedAt sets the "updated_at" field.
func (ec *ExclusionCreate) SetUpdatedAt(t time.Time) *ExclusionCreate {
	ec.mutation.SetUpdatedAt(t)
	return ec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ec *ExclusionCreate) SetNillableUpdatedAt(t *time.Time) *ExclusionCreate {
	if t != nil {
		ec.SetUpdatedAt(*t)
	}
	return ec
}

// SetTenantID sets the "tenant_id" field.
func (ec *ExclusionCreate) SetTenantID(i int64) *ExclusionCreate {
	ec.mutation.SetTenantID(i)
	return ec
}

// SetBrandName sets the "brand_name" field.
func (ec *ExclusionCreate) SetBrandName(s string) *ExclusionCreate {
	ec.mutation.SetBrandName(s)
	return ec
}

// SetSkuIds sets the "sku_ids" field.
func (ec *ExclusionCreate) SetSkuIds(i []int64) *ExclusionCreate {
	ec.mutation.SetSkuIds(i)
	return ec
}

// SetStartDate sets the "start_date" field.
func (ec *ExclusionCreate) SetStartDate(t time.Time) *ExclusionCreate {
	ec.mutation.SetStartDate(t)
	return ec
}

// SetEndDate sets the "end_date" field.
func (ec *ExclusionCreate) SetEndDate(t time.Time) *ExclusionCreate {
	ec.mutation.SetEndDate(t)
	return ec
}

// SetCreatedBy sets the "created_by" field.
func (ec *ExclusionCreate) SetCreatedBy(i int64) *ExclusionCreate {
	ec.mutation.SetCreatedBy(i)
	return ec
}

// SetID sets the "id" field.
func (ec *ExclusionCreate) SetID(i int64) *ExclusionCreate {
	ec.mutation.SetID(i)
	return ec
}

// Mutation returns the ExclusionMutation object of the builder.
func (ec *ExclusionCreate) Mutation() *ExclusionMutation {
	return ec.mutation
}

// Save creates the Exclusion in the database.
func (ec *ExclusionCreate) Save(ctx context.Context) (*Exclusion, error) {
	ec.defaults()
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *ExclusionCreate) SaveX(ctx context.Context) *Exclusion {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *ExclusionCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *ExclusionCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *ExclusionCreate) defaults() {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		v := exclusion.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		v := exclusion.DefaultUpdatedAt()
		ec.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *ExclusionCreate) check() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Exclusion.created_at"`)}
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Exclusion.updated_at"`)}
	}
	if _, ok := ec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Exclusion.tenant_id"`)}
	}
	if _, ok := ec.mutation.BrandName(); !ok {
		return &ValidationError{Name: "brand_name", err: errors.New(`ent: missing required field "Exclusion.brand_name"`)}
	}
	if v, ok := ec.mutation.BrandName(); ok {
		if err := exclusion.BrandNameValidator(v); err != nil {
			return &ValidationError{Name: "brand_name", err: fmt.Errorf(`ent: validator failed for field "Exclusion.brand_name": %w`, err)}
		}
	}
	if _, ok := ec.mutation.SkuIds(); !ok {
		return &ValidationError{Name: "sku_ids", err: errors.New(`ent: missing required field "Exclusion.sku_ids"`)}
	}
	if _, ok := ec.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Exclusion.start_date"`)}
	}
	if _, ok := ec.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "Exclusion.end_date"`)}
	}
	if _, ok := ec.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "Exclusion.created_by"`)}
	}
	return nil
}

func (ec *ExclusionCreate) sqlSave(ctx context.Context) (*Exclusion, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *ExclusionCreate) createSpec() (*Exclusion, *sqlgraph.CreateSpec) {
	var (
		_node = &Exclusion{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(exclusion.Table, sqlgraph.NewFieldSpec(exclusion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ec.conflict
	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(exclusion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.SetField(exclusion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.TenantID(); ok {
		_spec.SetField(exclusion.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := ec.mutation.BrandName(); ok {
		_spec.SetField(exclusion.FieldBrandName, field.TypeString, value)
		_node.BrandName = value
	}
	if value, ok := ec.mutation.SkuIds(); ok {
		_spec.SetField(exclusion.FieldSkuIds, field.TypeJSON, value)
		_node.SkuIds = value
	}
	if value, ok := ec.mutation.StartDate(); ok {
		_spec.SetField(exclusion.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := ec.mutation.EndDate(); ok {
		_spec.SetField(exclusion.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := ec.mutation.CreatedBy(); ok {
		_spec.SetField(exclusion.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Exclusion.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExclusionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ec *ExclusionCreate) OnConflict(opts ...sql.ConflictOption) *ExclusionUpsertOne {
	ec.conflict = opts
	return &ExclusionUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ec *ExclusionCreate) OnConflictColumns(columns ...string) *ExclusionUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &ExclusionUpsertOne{
		create: ec,
	}
}

type (
	// ExclusionUpsertOne is the builder for "upsert"-ing
	//  one Exclusion node.
	ExclusionUpsertOne struct {
		create *ExclusionCreate
	}

	// ExclusionUpsert is the "OnConflict" setter.
	ExclusionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExclusionUpsert) SetUpdatedAt(v time.Time) *ExclusionUpsert {
	u.Set(exclusion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateUpdatedAt() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldUpdatedAt)
	return u
}

// SetBrandName sets the "brand_name" field.
func (u *ExclusionUpsert) SetBrandName(v string) *ExclusionUpsert {
	u.Set(exclusion.FieldBrandName, v)
	return u
}

// UpdateBrandName sets the "brand_name" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateBrandName() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldBrandName)
	return u
}

// SetSkuIds sets the "sku_ids" field.
func (u *ExclusionUpsert) SetSkuIds(v []int64) *ExclusionUpsert {
	u.Set(exclusion.FieldSkuIds, v)
	return u
}

// UpdateSkuIds sets the "sku_ids" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateSkuIds() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldSkuIds)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *ExclusionUpsert) SetStartDate(v time.Time) *ExclusionUpsert {
	u.Set(exclusion.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateStartDate() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldStartDate)
	return u
}

// SetEndDate sets the "end_date" field.
func (u *ExclusionUpsert) SetEndDate(v time.Time) *ExclusionUpsert {
	u.Set(exclusion.FieldEndDate, v)
	return u
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateEndDate() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldEndDate)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ExclusionUpsert) SetCreatedBy(v int64) *ExclusionUpsert {
	u.Set(exclusion.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExclusionUpsert) UpdateCreatedBy() *ExclusionUpsert {
	u.SetExcluded(exclusion.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExclusionUpsert) AddCreatedBy(v int64) *ExclusionUpsert {
	u.Add(exclusion.FieldCreatedBy, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exclusion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExclusionUpsertOne) UpdateNewValues() *ExclusionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(exclusion.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(exclusion.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(exclusion.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExclusionUpsertOne) Ignore() *ExclusionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExclusionUpsertOne) DoNothing() *ExclusionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExclusionCreate.OnConflict
// documentation for more info.
func (u *ExclusionUpsertOne) Update(set func(*ExclusionUpsert)) *ExclusionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExclusionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExclusionUpsertOne) SetUpdatedAt(v time.Time) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateUpdatedAt() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBrandName sets the "brand_name" field.
func (u *ExclusionUpsertOne) SetBrandName(v string) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetBrandName(v)
	})
}

// UpdateBrandName sets the "brand_name" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateBrandName() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateBrandName()
	})
}

// SetSkuIds sets the "sku_ids" field.
func (u *ExclusionUpsertOne) SetSkuIds(v []int64) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetSkuIds(v)
	})
}

// UpdateSkuIds sets the "sku_ids" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateSkuIds() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateSkuIds()
	})
}

// SetStartDate sets the "start_date" field.
func (u *ExclusionUpsertOne) SetStartDate(v time.Time) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateStartDate() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *ExclusionUpsertOne) SetEndDate(v time.Time) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateEndDate() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateEndDate()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExclusionUpsertOne) SetCreatedBy(v int64) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExclusionUpsertOne) AddCreatedBy(v int64) *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExclusionUpsertOne) UpdateCreatedBy() *ExclusionUpsertOne {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *ExclusionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExclusionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExclusionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExclusionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExclusionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExclusionCreateBulk is the builder for creating many Exclusion entities in bulk.
type ExclusionCreateBulk struct {
	config
	err      error
	builders []*ExclusionCreate
	conflict []sql.ConflictOption
}

// Save creates the Exclusion entities in the database.
func (ecb *ExclusionCreateBulk) Save(ctx context.Context) ([]*Exclusion, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Exclusion, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExclusionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *ExclusionCreateBulk) SaveX(ctx context.Context) []*Exclusion {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *ExclusionCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *ExclusionCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Exclusion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExclusionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ecb *ExclusionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExclusionUpsertBulk {
	ecb.conflict = opts
	return &ExclusionUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ecb *ExclusionCreateBulk) OnConflictColumns(columns ...string) *ExclusionUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &ExclusionUpsertBulk{
		create: ecb,
	}
}

// ExclusionUpsertBulk is the builder for "upsert"-ing
// a bulk of Exclusion nodes.
type ExclusionUpsertBulk struct {
	create *ExclusionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(exclusion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExclusionUpsertBulk) UpdateNewValues() *ExclusionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(exclusion.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(exclusion.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(exclusion.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Exclusion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExclusionUpsertBulk) Ignore() *ExclusionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExclusionUpsertBulk) DoNothing() *ExclusionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExclusionCreateBulk.OnConflict
// documentation for more info.
func (u *ExclusionUpsertBulk) Update(set func(*ExclusionUpsert)) *ExclusionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExclusionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExclusionUpsertBulk) SetUpdatedAt(v time.Time) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateUpdatedAt() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetBrandName sets the "brand_name" field.
func (u *ExclusionUpsertBulk) SetBrandName(v string) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetBrandName(v)
	})
}

// UpdateBrandName sets the "brand_name" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateBrandName() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateBrandName()
	})
}

// SetSkuIds sets the "sku_ids" field.
func (u *ExclusionUpsertBulk) SetSkuIds(v []int64) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetSkuIds(v)
	})
}

// UpdateSkuIds sets the "sku_ids" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateSkuIds() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateSkuIds()
	})
}

// SetStartDate sets the "start_date" field.
func (u *ExclusionUpsertBulk) SetStartDate(v time.Time) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateStartDate() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *ExclusionUpsertBulk) SetEndDate(v time.Time) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateEndDate() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateEndDate()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ExclusionUpsertBulk) SetCreatedBy(v int64) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *ExclusionUpsertBulk) AddCreatedBy(v int64) *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ExclusionUpsertBulk) UpdateCreatedBy() *ExclusionUpsertBulk {
	return u.Update(func(s *ExclusionUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *ExclusionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExclusionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExclusionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExclusionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
