// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/platform-billing/ent/commission"
	"gitlab.calendaria.team/services/platform-billing/ent/enum"
	"gitlab.calendaria.team/services/platform-billing/ent/exclusion"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
	"gitlab.calendaria.team/services/platform-billing/ent/saleevent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCommission = "Commission"
	TypeExclusion  = "Exclusion"
	TypeSaleEvent  = "SaleEvent"
)

// CommissionMutation represents an operation that mutates the Commission nodes in the graph.
type CommissionMutation struct {
	config
	op                    Op
	typ                   string
	id                    *int64
	created_at            *time.Time
	updated_at            *time.Time
	tenant_id             *int64
	addtenant_id          *int64
	period_start          *time.Time
	period_end            *time.Time
	gmv                   *decimal.Decimal
	addgmv                *decimal.Decimal
	excluded_amount       *decimal.Decimal
	addexcluded_amount    *decimal.Decimal
	taxable_amount        *decimal.Decimal
	addtaxable_amount     *decimal.Decimal
	rate                  *decimal.Decimal
	addrate               *decimal.Decimal
	commission            *decimal.Decimal
	addcommission         *decimal.Decimal
	manager_share_rate    *decimal.Decimal
	addmanager_share_rate *decimal.Decimal
	manager_share         *decimal.Decimal
	addmanager_share      *decimal.Decimal
	status                *enum.CommissionStatus
	clearedFields         map[string]struct{}
	done                  bool
	oldValue              func(context.Context) (*Commission, error)
	predicates            []predicate.Commission
}

var _ ent.Mutation = (*CommissionMutation)(nil)

// commissionOption allows management of the mutation configuration using functional options.
type commissionOption func(*CommissionMutation)

// newCommissionMutation creates new mutation for the Commission entity.
func newCommissionMutation(c config, op Op, opts ...commissionOption) *CommissionMutation {
	m := &CommissionMutation{
		config:        c,
		op:            op,
		typ:           TypeCommission,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCommissionID sets the ID field of the mutation.
func withCommissionID(id int64) commissionOption {
	return func(m *CommissionMutation) {
		var (
			err   error
			once  sync.Once
			value *Commission
		)
		m.oldValue = func(ctx context.Context) (*Commission, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Commission.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCommission sets the old Commission of the mutation.
func withCommission(node *Commission) commissionOption {
	return func(m *CommissionMutation) {
		m.oldValue = func(context.Context) (*Commission, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CommissionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CommissionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Commission entities.
func (m *CommissionMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CommissionMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CommissionMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Commission.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *CommissionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *CommissionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *CommissionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *CommissionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *CommissionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *CommissionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTenantID sets the "tenant_id" field.
func (m *CommissionMutation) SetTenantID(i int64) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *CommissionMutation) TenantID() (r int64, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldTenantID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *CommissionMutation) AddTenantID(i int64) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *CommissionMutation) AddedTenantID() (r int64, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *CommissionMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
}

// SetPeriodStart sets the "period_start" field.
func (m *CommissionMutation) SetPeriodStart(t time.Time) {
	m.period_start = &t
}

// PeriodStart returns the value of the "period_start" field in the mutation.
func (m *CommissionMutation) PeriodStart() (r time.Time, exists bool) {
	v := m.period_start
	if v == nil {
		return
	}
	return *v, true
}

// OldPeriodStart returns the old "period_start" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldPeriodStart(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPeriodStart is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPeriodStart requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPeriodStart: %w", err)
	}
	return oldValue.PeriodStart, nil
}

// ResetPeriodStart resets all changes to the "period_start" field.
func (m *CommissionMutation) ResetPeriodStart() {
	m.period_start = nil
}

// SetPeriodEnd sets the "period_end" field.
func (m *CommissionMutation) SetPeriodEnd(t time.Time) {
	m.period_end = &t
}

// PeriodEnd returns the value of the "period_end" field in the mutation.
func (m *CommissionMutation) PeriodEnd() (r time.Time, exists bool) {
	v := m.period_end
	if v == nil {
		return
	}
	return *v, true
}

// OldPeriodEnd returns the old "period_end" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldPeriodEnd(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPeriodEnd is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPeriodEnd requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPeriodEnd: %w", err)
	}
	return oldValue.PeriodEnd, nil
}

// ResetPeriodEnd resets all changes to the "period_end" field.
func (m *CommissionMutation) ResetPeriodEnd() {
	m.period_end = nil
}

// SetGmv sets the "gmv" field.
func (m *CommissionMutation) SetGmv(d decimal.Decimal) {
	m.gmv = &d
	m.addgmv = nil
}

// Gmv returns the value of the "gmv" field in the mutation.
func (m *CommissionMutation) Gmv() (r decimal.Decimal, exists bool) {
	v := m.gmv
	if v == nil {
		return
	}
	return *v, true
}

// OldGmv returns the old "gmv" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldGmv(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGmv is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGmv requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGmv: %w", err)
	}
	return oldValue.Gmv, nil
}

// AddGmv adds d to the "gmv" field.
func (m *CommissionMutation) AddGmv(d decimal.Decimal) {
	if m.addgmv != nil {
		*m.addgmv = m.addgmv.Add(d)
	} else {
		m.addgmv = &d
	}
}

// AddedGmv returns the value that was added to the "gmv" field in this mutation.
func (m *CommissionMutation) AddedGmv() (r decimal.Decimal, exists bool) {
	v := m.addgmv
	if v == nil {
		return
	}
	return *v, true
}

// ClearGmv clears the value of the "gmv" field.
func (m *CommissionMutation) ClearGmv() {
	m.gmv = nil
	m.addgmv = nil
	m.clearedFields[commission.FieldGmv] = struct{}{}
}

// GmvCleared returns if the "gmv" field was cleared in this mutation.
func (m *CommissionMutation) GmvCleared() bool {
	_, ok := m.clearedFields[commission.FieldGmv]
	return ok
}

// ResetGmv resets all changes to the "gmv" field.
func (m *CommissionMutation) ResetGmv() {
	m.gmv = nil
	m.addgmv = nil
	delete(m.clearedFields, commission.FieldGmv)
}

// SetExcludedAmount sets the "excluded_amount" field.
func (m *CommissionMutation) SetExcludedAmount(d decimal.Decimal) {
	m.excluded_amount = &d
	m.addexcluded_amount = nil
}

// ExcludedAmount returns the value of the "excluded_amount" field in the mutation.
func (m *CommissionMutation) ExcludedAmount() (r decimal.Decimal, exists bool) {
	v := m.excluded_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldExcludedAmount returns the old "excluded_amount" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldExcludedAmount(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExcludedAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExcludedAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExcludedAmount: %w", err)
	}
	return oldValue.ExcludedAmount, nil
}

// AddExcludedAmount adds d to the "excluded_amount" field.
func (m *CommissionMutation) AddExcludedAmount(d decimal.Decimal) {
	if m.addexcluded_amount != nil {
		*m.addexcluded_amount = m.addexcluded_amount.Add(d)
	} else {
		m.addexcluded_amount = &d
	}
}

// AddedExcludedAmount returns the value that was added to the "excluded_amount" field in this mutation.
func (m *CommissionMutation) AddedExcludedAmount() (r decimal.Decimal, exists bool) {
	v := m.addexcluded_amount
	if v == nil {
		return
	}
	return *v, true
}

// ClearExcludedAmount clears the value of the "excluded_amount" field.
func (m *CommissionMutation) ClearExcludedAmount() {
	m.excluded_amount = nil
	m.addexcluded_amount = nil
	m.clearedFields[commission.FieldExcludedAmount] = struct{}{}
}

// ExcludedAmountCleared returns if the "excluded_amount" field was cleared in this mutation.
func (m *CommissionMutation) ExcludedAmountCleared() bool {
	_, ok := m.clearedFields[commission.FieldExcludedAmount]
	return ok
}

// ResetExcludedAmount resets all changes to the "excluded_amount" field.
func (m *CommissionMutation) ResetExcludedAmount() {
	m.excluded_amount = nil
	m.addexcluded_amount = nil
	delete(m.clearedFields, commission.FieldExcludedAmount)
}

// SetTaxableAmount sets the "taxable_amount" field.
func (m *CommissionMutation) SetTaxableAmount(d decimal.Decimal) {
	m.taxable_amount = &d
	m.addtaxable_amount = nil
}

// TaxableAmount returns the value of the "taxable_amount" field in the mutation.
func (m *CommissionMutation) TaxableAmount() (r decimal.Decimal, exists bool) {
	v := m.taxable_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldTaxableAmount returns the old "taxable_amount" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldTaxableAmount(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTaxableAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTaxableAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTaxableAmount: %w", err)
	}
	return oldValue.TaxableAmount, nil
}

// AddTaxableAmount adds d to the "taxable_amount" field.
func (m *CommissionMutation) AddTaxableAmount(d decimal.Decimal) {
	if m.addtaxable_amount != nil {
		*m.addtaxable_amount = m.addtaxable_amount.Add(d)
	} else {
		m.addtaxable_amount = &d
	}
}

// AddedTaxableAmount returns the value that was added to the "taxable_amount" field in this mutation.
func (m *CommissionMutation) AddedTaxableAmount() (r decimal.Decimal, exists bool) {
	v := m.addtaxable_amount
	if v == nil {
		return
	}
	return *v, true
}

// ClearTaxableAmount clears the value of the "taxable_amount" field.
func (m *CommissionMutation) ClearTaxableAmount() {
	m.taxable_amount = nil
	m.addtaxable_amount = nil
	m.clearedFields[commission.FieldTaxableAmount] = struct{}{}
}

// TaxableAmountCleared returns if the "taxable_amount" field was cleared in this mutation.
func (m *CommissionMutation) TaxableAmountCleared() bool {
	_, ok := m.clearedFields[commission.FieldTaxableAmount]
	return ok
}

// ResetTaxableAmount resets all changes to the "taxable_amount" field.
func (m *CommissionMutation) ResetTaxableAmount() {
	m.taxable_amount = nil
	m.addtaxable_amount = nil
	delete(m.clearedFields, commission.FieldTaxableAmount)
}

// SetRate sets the "rate" field.
func (m *CommissionMutation) SetRate(d decimal.Decimal) {
	m.rate = &d
	m.addrate = nil
}

// Rate returns the value of the "rate" field in the mutation.
func (m *CommissionMutation) Rate() (r decimal.Decimal, exists bool) {
	v := m.rate
	if v == nil {
		return
	}
	return *v, true
}

// OldRate returns the old "rate" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldRate(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRate: %w", err)
	}
	return oldValue.Rate, nil
}

// AddRate adds d to the "rate" field.
func (m *CommissionMutation) AddRate(d decimal.Decimal) {
	if m.addrate != nil {
		*m.addrate = m.addrate.Add(d)
	} else {
		m.addrate = &d
	}
}

// AddedRate returns the value that was added to the "rate" field in this mutation.
func (m *CommissionMutation) AddedRate() (r decimal.Decimal, exists bool) {
	v := m.addrate
	if v == nil {
		return
	}
	return *v, true
}

// ClearRate clears the value of the "rate" field.
func (m *CommissionMutation) ClearRate() {
	m.rate = nil
	m.addrate = nil
	m.clearedFields[commission.FieldRate] = struct{}{}
}

// RateCleared returns if the "rate" field was cleared in this mutation.
func (m *CommissionMutation) RateCleared() bool {
	_, ok := m.clearedFields[commission.FieldRate]
	return ok
}

// ResetRate resets all changes to the "rate" field.
func (m *CommissionMutation) ResetRate() {
	m.rate = nil
	m.addrate = nil
	delete(m.clearedFields, commission.FieldRate)
}

// SetCommission sets the "commission" field.
func (m *CommissionMutation) SetCommission(d decimal.Decimal) {
	m.commission = &d
	m.addcommission = nil
}

// Commission returns the value of the "commission" field in the mutation.
func (m *CommissionMutation) Commission() (r decimal.Decimal, exists bool) {
	v := m.commission
	if v == nil {
		return
	}
	return *v, true
}

// OldCommission returns the old "commission" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldCommission(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCommission is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCommission requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCommission: %w", err)
	}
	return oldValue.Commission, nil
}

// AddCommission adds d to the "commission" field.
func (m *CommissionMutation) AddCommission(d decimal.Decimal) {
	if m.addcommission != nil {
		*m.addcommission = m.addcommission.Add(d)
	} else {
		m.addcommission = &d
	}
}

// AddedCommission returns the value that was added to the "commission" field in this mutation.
func (m *CommissionMutation) AddedCommission() (r decimal.Decimal, exists bool) {
	v := m.addcommission
	if v == nil {
		return
	}
	return *v, true
}

// ClearCommission clears the value of the "commission" field.
func (m *CommissionMutation) ClearCommission() {
	m.commission = nil
	m.addcommission = nil
	m.clearedFields[commission.FieldCommission] = struct{}{}
}

// CommissionCleared returns if the "commission" field was cleared in this mutation.
func (m *CommissionMutation) CommissionCleared() bool {
	_, ok := m.clearedFields[commission.FieldCommission]
	return ok
}

// ResetCommission resets all changes to the "commission" field.
func (m *CommissionMutation) ResetCommission() {
	m.commission = nil
	m.addcommission = nil
	delete(m.clearedFields, commission.FieldCommission)
}

// SetManagerShareRate sets the "manager_share_rate" field.
func (m *CommissionMutation) SetManagerShareRate(d decimal.Decimal) {
	m.manager_share_rate = &d
	m.addmanager_share_rate = nil
}

// ManagerShareRate returns the value of the "manager_share_rate" field in the mutation.
func (m *CommissionMutation) ManagerShareRate() (r decimal.Decimal, exists bool) {
	v := m.manager_share_rate
	if v == nil {
		return
	}
	return *v, true
}

// OldManagerShareRate returns the old "manager_share_rate" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldManagerShareRate(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManagerShareRate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManagerShareRate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManagerShareRate: %w", err)
	}
	return oldValue.ManagerShareRate, nil
}

// AddManagerShareRate adds d to the "manager_share_rate" field.
func (m *CommissionMutation) AddManagerShareRate(d decimal.Decimal) {
	if m.addmanager_share_rate != nil {
		*m.addmanager_share_rate = m.addmanager_share_rate.Add(d)
	} else {
		m.addmanager_share_rate = &d
	}
}

// AddedManagerShareRate returns the value that was added to the "manager_share_rate" field in this mutation.
func (m *CommissionMutation) AddedManagerShareRate() (r decimal.Decimal, exists bool) {
	v := m.addmanager_share_rate
	if v == nil {
		return
	}
	return *v, true
}

// ClearManagerShareRate clears the value of the "manager_share_rate" field.
func (m *CommissionMutation) ClearManagerShareRate() {
	m.manager_share_rate = nil
	m.addmanager_share_rate = nil
	m.clearedFields[commission.FieldManagerShareRate] = struct{}{}
}

// ManagerShareRateCleared returns if the "manager_share_rate" field was cleared in this mutation.
func (m *CommissionMutation) ManagerShareRateCleared() bool {
	_, ok := m.clearedFields[commission.FieldManagerShareRate]
	return ok
}

// ResetManagerShareRate resets all changes to the "manager_share_rate" field.
func (m *CommissionMutation) ResetManagerShareRate() {
	m.manager_share_rate = nil
	m.addmanager_share_rate = nil
	delete(m.clearedFields, commission.FieldManagerShareRate)
}

// SetManagerShare sets the "manager_share" field.
func (m *CommissionMutation) SetManagerShare(d decimal.Decimal) {
	m.manager_share = &d
	m.addmanager_share = nil
}

// ManagerShare returns the value of the "manager_share" field in the mutation.
func (m *CommissionMutation) ManagerShare() (r decimal.Decimal, exists bool) {
	v := m.manager_share
	if v == nil {
		return
	}
	return *v, true
}

// OldManagerShare returns the old "manager_share" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldManagerShare(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldManagerShare is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldManagerShare requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldManagerShare: %w", err)
	}
	return oldValue.ManagerShare, nil
}

// AddManagerShare adds d to the "manager_share" field.
func (m *CommissionMutation) AddManagerShare(d decimal.Decimal) {
	if m.addmanager_share != nil {
		*m.addmanager_share = m.addmanager_share.Add(d)
	} else {
		m.addmanager_share = &d
	}
}

// AddedManagerShare returns the value that was added to the "manager_share" field in this mutation.
func (m *CommissionMutation) AddedManagerShare() (r decimal.Decimal, exists bool) {
	v := m.addmanager_share
	if v == nil {
		return
	}
	return *v, true
}

// ClearManagerShare clears the value of the "manager_share" field.
func (m *CommissionMutation) ClearManagerShare() {
	m.manager_share = nil
	m.addmanager_share = nil
	m.clearedFields[commission.FieldManagerShare] = struct{}{}
}

// ManagerShareCleared returns if the "manager_share" field was cleared in this mutation.
func (m *CommissionMutation) ManagerShareCleared() bool {
	_, ok := m.clearedFields[commission.FieldManagerShare]
	return ok
}

// ResetManagerShare resets all changes to the "manager_share" field.
func (m *CommissionMutation) ResetManagerShare() {
	m.manager_share = nil
	m.addmanager_share = nil
	delete(m.clearedFields, commission.FieldManagerShare)
}

// SetStatus sets the "status" field.
func (m *CommissionMutation) SetStatus(es enum.CommissionStatus) {
	m.status = &es
}

// Status returns the value of the "status" field in the mutation.
func (m *CommissionMutation) Status() (r enum.CommissionStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the Commission entity.
// If the Commission object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CommissionMutation) OldStatus(ctx context.Context) (v enum.CommissionStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *CommissionMutation) ResetStatus() {
	m.status = nil
}

// Where appends a list predicates to the CommissionMutation builder.
func (m *CommissionMutation) Where(ps ...predicate.Commission) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CommissionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CommissionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Commission, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CommissionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CommissionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Commission).
func (m *CommissionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CommissionMutation) Fields() []string {
	fields := make([]string, 0, 13)
	if m.created_at != nil {
		fields = append(fields, commission.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, commission.FieldUpdatedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, commission.FieldTenantID)
	}
	if m.period_start != nil {
		fields = append(fields, commission.FieldPeriodStart)
	}
	if m.period_end != nil {
		fields = append(fields, commission.FieldPeriodEnd)
	}
	if m.gmv != nil {
		fields = append(fields, commission.FieldGmv)
	}
	if m.excluded_amount != nil {
		fields = append(fields, commission.FieldExcludedAmount)
	}
	if m.taxable_amount != nil {
		fields = append(fields, commission.FieldTaxableAmount)
	}
	if m.rate != nil {
		fields = append(fields, commission.FieldRate)
	}
	if m.commission != nil {
		fields = append(fields, commission.FieldCommission)
	}
	if m.manager_share_rate != nil {
		fields = append(fields, commission.FieldManagerShareRate)
	}
	if m.manager_share != nil {
		fields = append(fields, commission.FieldManagerShare)
	}
	if m.status != nil {
		fields = append(fields, commission.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CommissionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case commission.FieldCreatedAt:
		return m.CreatedAt()
	case commission.FieldUpdatedAt:
		return m.UpdatedAt()
	case commission.FieldTenantID:
		return m.TenantID()
	case commission.FieldPeriodStart:
		return m.PeriodStart()
	case commission.FieldPeriodEnd:
		return m.PeriodEnd()
	case commission.FieldGmv:
		return m.Gmv()
	case commission.FieldExcludedAmount:
		return m.ExcludedAmount()
	case commission.FieldTaxableAmount:
		return m.TaxableAmount()
	case commission.FieldRate:
		return m.Rate()
	case commission.FieldCommission:
		return m.Commission()
	case commission.FieldManagerShareRate:
		return m.ManagerShareRate()
	case commission.FieldManagerShare:
		return m.ManagerShare()
	case commission.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CommissionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case commission.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case commission.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case commission.FieldTenantID:
		return m.OldTenantID(ctx)
	case commission.FieldPeriodStart:
		return m.OldPeriodStart(ctx)
	case commission.FieldPeriodEnd:
		return m.OldPeriodEnd(ctx)
	case commission.FieldGmv:
		return m.OldGmv(ctx)
	case commission.FieldExcludedAmount:
		return m.OldExcludedAmount(ctx)
	case commission.FieldTaxableAmount:
		return m.OldTaxableAmount(ctx)
	case commission.FieldRate:
		return m.OldRate(ctx)
	case commission.FieldCommission:
		return m.OldCommission(ctx)
	case commission.FieldManagerShareRate:
		return m.OldManagerShareRate(ctx)
	case commission.FieldManagerShare:
		return m.OldManagerShare(ctx)
	case commission.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown Commission field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CommissionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case commission.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case commission.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case commission.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case commission.FieldPeriodStart:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPeriodStart(v)
		return nil
	case commission.FieldPeriodEnd:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPeriodEnd(v)
		return nil
	case commission.FieldGmv:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGmv(v)
		return nil
	case commission.FieldExcludedAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExcludedAmount(v)
		return nil
	case commission.FieldTaxableAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTaxableAmount(v)
		return nil
	case commission.FieldRate:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRate(v)
		return nil
	case commission.FieldCommission:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCommission(v)
		return nil
	case commission.FieldManagerShareRate:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManagerShareRate(v)
		return nil
	case commission.FieldManagerShare:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetManagerShare(v)
		return nil
	case commission.FieldStatus:
		v, ok := value.(enum.CommissionStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown Commission field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CommissionMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, commission.FieldTenantID)
	}
	if m.addgmv != nil {
		fields = append(fields, commission.FieldGmv)
	}
	if m.addexcluded_amount != nil {
		fields = append(fields, commission.FieldExcludedAmount)
	}
	if m.addtaxable_amount != nil {
		fields = append(fields, commission.FieldTaxableAmount)
	}
	if m.addrate != nil {
		fields = append(fields, commission.FieldRate)
	}
	if m.addcommission != nil {
		fields = append(fields, commission.FieldCommission)
	}
	if m.addmanager_share_rate != nil {
		fields = append(fields, commission.FieldManagerShareRate)
	}
	if m.addmanager_share != nil {
		fields = append(fields, commission.FieldManagerShare)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CommissionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case commission.FieldTenantID:
		return m.AddedTenantID()
	case commission.FieldGmv:
		return m.AddedGmv()
	case commission.FieldExcludedAmount:
		return m.AddedExcludedAmount()
	case commission.FieldTaxableAmount:
		return m.AddedTaxableAmount()
	case commission.FieldRate:
		return m.AddedRate()
	case commission.FieldCommission:
		return m.AddedCommission()
	case commission.FieldManagerShareRate:
		return m.AddedManagerShareRate()
	case commission.FieldManagerShare:
		return m.AddedManagerShare()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CommissionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case commission.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case commission.FieldGmv:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddGmv(v)
		return nil
	case commission.FieldExcludedAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddExcludedAmount(v)
		return nil
	case commission.FieldTaxableAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTaxableAmount(v)
		return nil
	case commission.FieldRate:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRate(v)
		return nil
	case commission.FieldCommission:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCommission(v)
		return nil
	case commission.FieldManagerShareRate:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddManagerShareRate(v)
		return nil
	case commission.FieldManagerShare:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddManagerShare(v)
		return nil
	}
	return fmt.Errorf("unknown Commission numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CommissionMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(commission.FieldGmv) {
		fields = append(fields, commission.FieldGmv)
	}
	if m.FieldCleared(commission.FieldExcludedAmount) {
		fields = append(fields, commission.FieldExcludedAmount)
	}
	if m.FieldCleared(commission.FieldTaxableAmount) {
		fields = append(fields, commission.FieldTaxableAmount)
	}
	if m.FieldCleared(commission.FieldRate) {
		fields = append(fields, commission.FieldRate)
	}
	if m.FieldCleared(commission.FieldCommission) {
		fields = append(fields, commission.FieldCommission)
	}
	if m.FieldCleared(commission.FieldManagerShareRate) {
		fields = append(fields, commission.FieldManagerShareRate)
	}
	if m.FieldCleared(commission.FieldManagerShare) {
		fields = append(fields, commission.FieldManagerShare)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CommissionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CommissionMutation) ClearField(name string) error {
	switch name {
	case commission.FieldGmv:
		m.ClearGmv()
		return nil
	case commission.FieldExcludedAmount:
		m.ClearExcludedAmount()
		return nil
	case commission.FieldTaxableAmount:
		m.ClearTaxableAmount()
		return nil
	case commission.FieldRate:
		m.ClearRate()
		return nil
	case commission.FieldCommission:
		m.ClearCommission()
		return nil
	case commission.FieldManagerShareRate:
		m.ClearManagerShareRate()
		return nil
	case commission.FieldManagerShare:
		m.ClearManagerShare()
		return nil
	}
	return fmt.Errorf("unknown Commission nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CommissionMutation) ResetField(name string) error {
	switch name {
	case commission.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case commission.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case commission.FieldTenantID:
		m.ResetTenantID()
		return nil
	case commission.FieldPeriodStart:
		m.ResetPeriodStart()
		return nil
	case commission.FieldPeriodEnd:
		m.ResetPeriodEnd()
		return nil
	case commission.FieldGmv:
		m.ResetGmv()
		return nil
	case commission.FieldExcludedAmount:
		m.ResetExcludedAmount()
		return nil
	case commission.FieldTaxableAmount:
		m.ResetTaxableAmount()
		return nil
	case commission.FieldRate:
		m.ResetRate()
		return nil
	case commission.FieldCommission:
		m.ResetCommission()
		return nil
	case commission.FieldManagerShareRate:
		m.ResetManagerShareRate()
		return nil
	case commission.FieldManagerShare:
		m.ResetManagerShare()
		return nil
	case commission.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown Commission field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CommissionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CommissionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CommissionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CommissionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CommissionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CommissionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CommissionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Commission unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CommissionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Commission edge %s", name)
}

// ExclusionMutation represents an operation that mutates the Exclusion nodes in the graph.
type ExclusionMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	created_at    *time.Time
	updated_at    *time.Time
	tenant_id     *int64
	addtenant_id  *int64
	brand_name    *string
	sku_ids       *[]int64
	appendsku_ids []int64
	start_date    *time.Time
	end_date      *time.Time
	created_by    *int64
	addcreated_by *int64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Exclusion, error)
	predicates    []predicate.Exclusion
}

var _ ent.Mutation = (*ExclusionMutation)(nil)

// exclusionOption allows management of the mutation configuration using functional options.
type exclusionOption func(*ExclusionMutation)

// newExclusionMutation creates new mutation for the Exclusion entity.
func newExclusionMutation(c config, op Op, opts ...exclusionOption) *ExclusionMutation {
	m := &ExclusionMutation{
		config:        c,
		op:            op,
		typ:           TypeExclusion,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withExclusionID sets the ID field of the mutation.
func withExclusionID(id int64) exclusionOption {
	return func(m *ExclusionMutation) {
		var (
			err   error
			once  sync.Once
			value *Exclusion
		)
		m.oldValue = func(ctx context.Context) (*Exclusion, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Exclusion.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withExclusion sets the old Exclusion of the mutation.
func withExclusion(node *Exclusion) exclusionOption {
	return func(m *ExclusionMutation) {
		m.oldValue = func(context.Context) (*Exclusion, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ExclusionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ExclusionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Exclusion entities.
func (m *ExclusionMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ExclusionMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ExclusionMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Exclusion.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *ExclusionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ExclusionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ExclusionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ExclusionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ExclusionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ExclusionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTenantID sets the "tenant_id" field.
func (m *ExclusionMutation) SetTenantID(i int64) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *ExclusionMutation) TenantID() (r int64, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldTenantID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *ExclusionMutation) AddTenantID(i int64) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *ExclusionMutation) AddedTenantID() (r int64, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *ExclusionMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
}

// SetBrandName sets the "brand_name" field.
func (m *ExclusionMutation) SetBrandName(s string) {
	m.brand_name = &s
}

// BrandName returns the value of the "brand_name" field in the mutation.
func (m *ExclusionMutation) BrandName() (r string, exists bool) {
	v := m.brand_name
	if v == nil {
		return
	}
	return *v, true
}

// OldBrandName returns the old "brand_name" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldBrandName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBrandName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBrandName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBrandName: %w", err)
	}
	return oldValue.BrandName, nil
}

// ResetBrandName resets all changes to the "brand_name" field.
func (m *ExclusionMutation) ResetBrandName() {
	m.brand_name = nil
}

// SetSkuIds sets the "sku_ids" field.
func (m *ExclusionMutation) SetSkuIds(i []int64) {
	m.sku_ids = &i
	m.appendsku_ids = nil
}

// SkuIds returns the value of the "sku_ids" field in the mutation.
func (m *ExclusionMutation) SkuIds() (r []int64, exists bool) {
	v := m.sku_ids
	if v == nil {
		return
	}
	return *v, true
}

// OldSkuIds returns the old "sku_ids" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldSkuIds(ctx context.Context) (v []int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSkuIds is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSkuIds requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSkuIds: %w", err)
	}
	return oldValue.SkuIds, nil
}

// AppendSkuIds adds i to the "sku_ids" field.
func (m *ExclusionMutation) AppendSkuIds(i []int64) {
	m.appendsku_ids = append(m.appendsku_ids, i...)
}

// AppendedSkuIds returns the list of values that were appended to the "sku_ids" field in this mutation.
func (m *ExclusionMutation) AppendedSkuIds() ([]int64, bool) {
	if len(m.appendsku_ids) == 0 {
		return nil, false
	}
	return m.appendsku_ids, true
}

// ResetSkuIds resets all changes to the "sku_ids" field.
func (m *ExclusionMutation) ResetSkuIds() {
	m.sku_ids = nil
	m.appendsku_ids = nil
}

// SetStartDate sets the "start_date" field.
func (m *ExclusionMutation) SetStartDate(t time.Time) {
	m.start_date = &t
}

// StartDate returns the value of the "start_date" field in the mutation.
func (m *ExclusionMutation) StartDate() (r time.Time, exists bool) {
	v := m.start_date
	if v == nil {
		return
	}
	return *v, true
}

// OldStartDate returns the old "start_date" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldStartDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartDate: %w", err)
	}
	return oldValue.StartDate, nil
}

// ResetStartDate resets all changes to the "start_date" field.
func (m *ExclusionMutation) ResetStartDate() {
	m.start_date = nil
}

// SetEndDate sets the "end_date" field.
func (m *ExclusionMutation) SetEndDate(t time.Time) {
	m.end_date = &t
}

// EndDate returns the value of the "end_date" field in the mutation.
func (m *ExclusionMutation) EndDate() (r time.Time, exists bool) {
	v := m.end_date
	if v == nil {
		return
	}
	return *v, true
}

// OldEndDate returns the old "end_date" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldEndDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEndDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEndDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEndDate: %w", err)
	}
	return oldValue.EndDate, nil
}

// ResetEndDate resets all changes to the "end_date" field.
func (m *ExclusionMutation) ResetEndDate() {
	m.end_date = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *ExclusionMutation) SetCreatedBy(i int64) {
	m.created_by = &i
	m.addcreated_by = nil
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *ExclusionMutation) CreatedBy() (r int64, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the Exclusion entity.
// If the Exclusion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExclusionMutation) OldCreatedBy(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// AddCreatedBy adds i to the "created_by" field.
func (m *ExclusionMutation) AddCreatedBy(i int64) {
	if m.addcreated_by != nil {
		*m.addcreated_by += i
	} else {
		m.addcreated_by = &i
	}
}

// AddedCreatedBy returns the value that was added to the "created_by" field in this mutation.
func (m *ExclusionMutation) AddedCreatedBy() (r int64, exists bool) {
	v := m.addcreated_by
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *ExclusionMutation) ResetCreatedBy() {
	m.created_by = nil
	m.addcreated_by = nil
}

// Where appends a list predicates to the ExclusionMutation builder.
func (m *ExclusionMutation) Where(ps ...predicate.Exclusion) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ExclusionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ExclusionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Exclusion, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ExclusionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ExclusionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Exclusion).
func (m *ExclusionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ExclusionMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.created_at != nil {
		fields = append(fields, exclusion.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, exclusion.FieldUpdatedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, exclusion.FieldTenantID)
	}
	if m.brand_name != nil {
		fields = append(fields, exclusion.FieldBrandName)
	}
	if m.sku_ids != nil {
		fields = append(fields, exclusion.FieldSkuIds)
	}
	if m.start_date != nil {
		fields = append(fields, exclusion.FieldStartDate)
	}
	if m.end_date != nil {
		fields = append(fields, exclusion.FieldEndDate)
	}
	if m.created_by != nil {
		fields = append(fields, exclusion.FieldCreatedBy)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ExclusionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case exclusion.FieldCreatedAt:
		return m.CreatedAt()
	case exclusion.FieldUpdatedAt:
		return m.UpdatedAt()
	case exclusion.FieldTenantID:
		return m.TenantID()
	case exclusion.FieldBrandName:
		return m.BrandName()
	case exclusion.FieldSkuIds:
		return m.SkuIds()
	case exclusion.FieldStartDate:
		return m.StartDate()
	case exclusion.FieldEndDate:
		return m.EndDate()
	case exclusion.FieldCreatedBy:
		return m.CreatedBy()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ExclusionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case exclusion.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case exclusion.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case exclusion.FieldTenantID:
		return m.OldTenantID(ctx)
	case exclusion.FieldBrandName:
		return m.OldBrandName(ctx)
	case exclusion.FieldSkuIds:
		return m.OldSkuIds(ctx)
	case exclusion.FieldStartDate:
		return m.OldStartDate(ctx)
	case exclusion.FieldEndDate:
		return m.OldEndDate(ctx)
	case exclusion.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	}
	return nil, fmt.Errorf("unknown Exclusion field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExclusionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case exclusion.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case exclusion.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case exclusion.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case exclusion.FieldBrandName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBrandName(v)
		return nil
	case exclusion.FieldSkuIds:
		v, ok := value.([]int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSkuIds(v)
		return nil
	case exclusion.FieldStartDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartDate(v)
		return nil
	case exclusion.FieldEndDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEndDate(v)
		return nil
	case exclusion.FieldCreatedBy:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	}
	return fmt.Errorf("unknown Exclusion field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ExclusionMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, exclusion.FieldTenantID)
	}
	if m.addcreated_by != nil {
		fields = append(fields, exclusion.FieldCreatedBy)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ExclusionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case exclusion.FieldTenantID:
		return m.AddedTenantID()
	case exclusion.FieldCreatedBy:
		return m.AddedCreatedBy()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExclusionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case exclusion.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case exclusion.FieldCreatedBy:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedBy(v)
		return nil
	}
	return fmt.Errorf("unknown Exclusion numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ExclusionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ExclusionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ExclusionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Exclusion nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ExclusionMutation) ResetField(name string) error {
	switch name {
	case exclusion.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case exclusion.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case exclusion.FieldTenantID:
		m.ResetTenantID()
		return nil
	case exclusion.FieldBrandName:
		m.ResetBrandName()
		return nil
	case exclusion.FieldSkuIds:
		m.ResetSkuIds()
		return nil
	case exclusion.FieldStartDate:
		m.ResetStartDate()
		return nil
	case exclusion.FieldEndDate:
		m.ResetEndDate()
		return nil
	case exclusion.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	}
	return fmt.Errorf("unknown Exclusion field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ExclusionMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ExclusionMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ExclusionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ExclusionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ExclusionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ExclusionMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ExclusionMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Exclusion unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ExclusionMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Exclusion edge %s", name)
}

// SaleEventMutation represents an operation that mutates the SaleEvent nodes in the graph.
type SaleEventMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	created_at    *time.Time
	updated_at    *time.Time
	tenant_id     *int64
	addtenant_id  *int64
	sale_id       *int64
	addsale_id    *int64
	product_id    *int64
	addproduct_id *int64
	amount        *decimal.Decimal
	addamount     *decimal.Decimal
	completed_at  *time.Time
	is_return     *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SaleEvent, error)
	predicates    []predicate.SaleEvent
}

var _ ent.Mutation = (*SaleEventMutation)(nil)

// saleeventOption allows management of the mutation configuration using functional options.
type saleeventOption func(*SaleEventMutation)

// newSaleEventMutation creates new mutation for the SaleEvent entity.
func newSaleEventMutation(c config, op Op, opts ...saleeventOption) *SaleEventMutation {
	m := &SaleEventMutation{
		config:        c,
		op:            op,
		typ:           TypeSaleEvent,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSaleEventID sets the ID field of the mutation.
func withSaleEventID(id int64) saleeventOption {
	return func(m *SaleEventMutation) {
		var (
			err   error
			once  sync.Once
			value *SaleEvent
		)
		m.oldValue = func(ctx context.Context) (*SaleEvent, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SaleEvent.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSaleEvent sets the old SaleEvent of the mutation.
func withSaleEvent(node *SaleEvent) saleeventOption {
	return func(m *SaleEventMutation) {
		m.oldValue = func(context.Context) (*SaleEvent, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SaleEventMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SaleEventMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SaleEvent entities.
func (m *SaleEventMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SaleEventMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SaleEventMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SaleEvent.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *SaleEventMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SaleEventMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SaleEventMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SaleEventMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SaleEventMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SaleEventMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetTenantID sets the "tenant_id" field.
func (m *SaleEventMutation) SetTenantID(i int64) {
	m.tenant_id = &i
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *SaleEventMutation) TenantID() (r int64, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldTenantID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds i to the "tenant_id" field.
func (m *SaleEventMutation) AddTenantID(i int64) {
	if m.addtenant_id != nil {
		*m.addtenant_id += i
	} else {
		m.addtenant_id = &i
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *SaleEventMutation) AddedTenantID() (r int64, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *SaleEventMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
}

// SetSaleID sets the "sale_id" field.
func (m *SaleEventMutation) SetSaleID(i int64) {
	m.sale_id = &i
	m.addsale_id = nil
}

// SaleID returns the value of the "sale_id" field in the mutation.
func (m *SaleEventMutation) SaleID() (r int64, exists bool) {
	v := m.sale_id
	if v == nil {
		return
	}
	return *v, true
}

// OldSaleID returns the old "sale_id" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldSaleID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSaleID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSaleID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSaleID: %w", err)
	}
	return oldValue.SaleID, nil
}

// AddSaleID adds i to the "sale_id" field.
func (m *SaleEventMutation) AddSaleID(i int64) {
	if m.addsale_id != nil {
		*m.addsale_id += i
	} else {
		m.addsale_id = &i
	}
}

// AddedSaleID returns the value that was added to the "sale_id" field in this mutation.
func (m *SaleEventMutation) AddedSaleID() (r int64, exists bool) {
	v := m.addsale_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetSaleID resets all changes to the "sale_id" field.
func (m *SaleEventMutation) ResetSaleID() {
	m.sale_id = nil
	m.addsale_id = nil
}

// SetProductID sets the "product_id" field.
func (m *SaleEventMutation) SetProductID(i int64) {
	m.product_id = &i
	m.addproduct_id = nil
}

// ProductID returns the value of the "product_id" field in the mutation.
func (m *SaleEventMutation) ProductID() (r int64, exists bool) {
	v := m.product_id
	if v == nil {
		return
	}
	return *v, true
}

// OldProductID returns the old "product_id" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldProductID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldProductID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldProductID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldProductID: %w", err)
	}
	return oldValue.ProductID, nil
}

// AddProductID adds i to the "product_id" field.
func (m *SaleEventMutation) AddProductID(i int64) {
	if m.addproduct_id != nil {
		*m.addproduct_id += i
	} else {
		m.addproduct_id = &i
	}
}

// AddedProductID returns the value that was added to the "product_id" field in this mutation.
func (m *SaleEventMutation) AddedProductID() (r int64, exists bool) {
	v := m.addproduct_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetProductID resets all changes to the "product_id" field.
func (m *SaleEventMutation) ResetProductID() {
	m.product_id = nil
	m.addproduct_id = nil
}

// SetAmount sets the "amount" field.
func (m *SaleEventMutation) SetAmount(d decimal.Decimal) {
	m.amount = &d
	m.addamount = nil
}

// Amount returns the value of the "amount" field in the mutation.
func (m *SaleEventMutation) Amount() (r decimal.Decimal, exists bool) {
	v := m.amount
	if v == nil {
		return
	}
	return *v, true
}

// OldAmount returns the old "amount" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldAmount(ctx context.Context) (v decimal.Decimal, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAmount: %w", err)
	}
	return oldValue.Amount, nil
}

// AddAmount adds d to the "amount" field.
func (m *SaleEventMutation) AddAmount(d decimal.Decimal) {
	if m.addamount != nil {
		*m.addamount = m.addamount.Add(d)
	} else {
		m.addamount = &d
	}
}

// AddedAmount returns the value that was added to the "amount" field in this mutation.
func (m *SaleEventMutation) AddedAmount() (r decimal.Decimal, exists bool) {
	v := m.addamount
	if v == nil {
		return
	}
	return *v, true
}

// ResetAmount resets all changes to the "amount" field.
func (m *SaleEventMutation) ResetAmount() {
	m.amount = nil
	m.addamount = nil
}

// SetCompletedAt sets the "completed_at" field.
func (m *SaleEventMutation) SetCompletedAt(t time.Time) {
	m.completed_at = &t
}

// CompletedAt returns the value of the "completed_at" field in the mutation.
func (m *SaleEventMutation) CompletedAt() (r time.Time, exists bool) {
	v := m.completed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCompletedAt returns the old "completed_at" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldCompletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompletedAt: %w", err)
	}
	return oldValue.CompletedAt, nil
}

// ResetCompletedAt resets all changes to the "completed_at" field.
func (m *SaleEventMutation) ResetCompletedAt() {
	m.completed_at = nil
}

// SetIsReturn sets the "is_return" field.
func (m *SaleEventMutation) SetIsReturn(b bool) {
	m.is_return = &b
}

// IsReturn returns the value of the "is_return" field in the mutation.
func (m *SaleEventMutation) IsReturn() (r bool, exists bool) {
	v := m.is_return
	if v == nil {
		return
	}
	return *v, true
}

// OldIsReturn returns the old "is_return" field's value of the SaleEvent entity.
// If the SaleEvent object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SaleEventMutation) OldIsReturn(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsReturn is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsReturn requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsReturn: %w", err)
	}
	return oldValue.IsReturn, nil
}

// ResetIsReturn resets all changes to the "is_return" field.
func (m *SaleEventMutation) ResetIsReturn() {
	m.is_return = nil
}

// Where appends a list predicates to the SaleEventMutation builder.
func (m *SaleEventMutation) Where(ps ...predicate.SaleEvent) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SaleEventMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SaleEventMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SaleEvent, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SaleEventMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SaleEventMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SaleEvent).
func (m *SaleEventMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SaleEventMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.created_at != nil {
		fields = append(fields, saleevent.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, saleevent.FieldUpdatedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, saleevent.FieldTenantID)
	}
	if m.sale_id != nil {
		fields = append(fields, saleevent.FieldSaleID)
	}
	if m.product_id != nil {
		fields = append(fields, saleevent.FieldProductID)
	}
	if m.amount != nil {
		fields = append(fields, saleevent.FieldAmount)
	}
	if m.completed_at != nil {
		fields = append(fields, saleevent.FieldCompletedAt)
	}
	if m.is_return != nil {
		fields = append(fields, saleevent.FieldIsReturn)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SaleEventMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case saleevent.FieldCreatedAt:
		return m.CreatedAt()
	case saleevent.FieldUpdatedAt:
		return m.UpdatedAt()
	case saleevent.FieldTenantID:
		return m.TenantID()
	case saleevent.FieldSaleID:
		return m.SaleID()
	case saleevent.FieldProductID:
		return m.ProductID()
	case saleevent.FieldAmount:
		return m.Amount()
	case saleevent.FieldCompletedAt:
		return m.CompletedAt()
	case saleevent.FieldIsReturn:
		return m.IsReturn()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SaleEventMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case saleevent.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case saleevent.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case saleevent.FieldTenantID:
		return m.OldTenantID(ctx)
	case saleevent.FieldSaleID:
		return m.OldSaleID(ctx)
	case saleevent.FieldProductID:
		return m.OldProductID(ctx)
	case saleevent.FieldAmount:
		return m.OldAmount(ctx)
	case saleevent.FieldCompletedAt:
		return m.OldCompletedAt(ctx)
	case saleevent.FieldIsReturn:
		return m.OldIsReturn(ctx)
	}
	return nil, fmt.Errorf("unknown SaleEvent field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SaleEventMutation) SetField(name string, value ent.Value) error {
	switch name {
	case saleevent.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case saleevent.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case saleevent.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case saleevent.FieldSaleID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSaleID(v)
		return nil
	case saleevent.FieldProductID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetProductID(v)
		return nil
	case saleevent.FieldAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAmount(v)
		return nil
	case saleevent.FieldCompletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompletedAt(v)
		return nil
	case saleevent.FieldIsReturn:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsReturn(v)
		return nil
	}
	return fmt.Errorf("unknown SaleEvent field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SaleEventMutation) AddedFields() []string {
	var fields []string
	if m.addtenant_id != nil {
		fields = append(fields, saleevent.FieldTenantID)
	}
	if m.addsale_id != nil {
		fields = append(fields, saleevent.FieldSaleID)
	}
	if m.addproduct_id != nil {
		fields = append(fields, saleevent.FieldProductID)
	}
	if m.addamount != nil {
		fields = append(fields, saleevent.FieldAmount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SaleEventMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case saleevent.FieldTenantID:
		return m.AddedTenantID()
	case saleevent.FieldSaleID:
		return m.AddedSaleID()
	case saleevent.FieldProductID:
		return m.AddedProductID()
	case saleevent.FieldAmount:
		return m.AddedAmount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SaleEventMutation) AddField(name string, value ent.Value) error {
	switch name {
	case saleevent.FieldTenantID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case saleevent.FieldSaleID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddSaleID(v)
		return nil
	case saleevent.FieldProductID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddProductID(v)
		return nil
	case saleevent.FieldAmount:
		v, ok := value.(decimal.Decimal)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAmount(v)
		return nil
	}
	return fmt.Errorf("unknown SaleEvent numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SaleEventMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SaleEventMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SaleEventMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SaleEvent nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SaleEventMutation) ResetField(name string) error {
	switch name {
	case saleevent.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case saleevent.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case saleevent.FieldTenantID:
		m.ResetTenantID()
		return nil
	case saleevent.FieldSaleID:
		m.ResetSaleID()
		return nil
	case saleevent.FieldProductID:
		m.ResetProductID()
		return nil
	case saleevent.FieldAmount:
		m.ResetAmount()
		return nil
	case saleevent.FieldCompletedAt:
		m.ResetCompletedAt()
		return nil
	case saleevent.FieldIsReturn:
		m.ResetIsReturn()
		return nil
	}
	return fmt.Errorf("unknown SaleEvent field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SaleEventMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SaleEventMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SaleEventMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SaleEventMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SaleEventMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SaleEventMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SaleEventMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SaleEvent unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SaleEventMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SaleEvent edge %s", name)
}
