// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"gitlab.calendaria.team/services/platform-billing/ent/commission"
	"gitlab.calendaria.team/services/platform-billing/ent/exclusion"
	"gitlab.calendaria.team/services/platform-billing/ent/saleevent"
	"gitlab.calendaria.team/services/platform-billing/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commissionMixin := schema.Commission{}.Mixin()
	commissionMixinFields0 := commissionMixin[0].Fields()
	_ = commissionMixinFields0
	commissionFields := schema.Commission{}.Fields()
	_ = commissionFields
	// commissionDescCreatedAt is the schema descriptor for created_at field.
	commissionDescCreatedAt := commissionMixinFields0[0].Descriptor()
	// commission.DefaultCreatedAt holds the default value on creation for the created_at field.
	commission.DefaultCreatedAt = commissionDescCreatedAt.Default.(func() time.Time)
	// commissionDescUpdatedAt is the schema descriptor for updated_at field.
	commissionDescUpdatedAt := commissionMixinFields0[1].Descriptor()
	// commission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	commission.DefaultUpdatedAt = commissionDescUpdatedAt.Default.(func() time.Time)
	// commission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	commission.UpdateDefaultUpdatedAt = commissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	exclusionMixin := schema.Exclusion{}.Mixin()
	exclusionMixinFields0 := exclusionMixin[0].Fields()
	_ = exclusionMixinFields0
	exclusionFields := schema.Exclusion{}.Fields()
	_ = exclusionFields
	// exclusionDescCreatedAt is the schema descriptor for created_at field.
	exclusionDescCreatedAt := exclusionMixinFields0[0].Descriptor()
	// exclusion.DefaultCreatedAt holds the default value on creation for the created_at field.
	exclusion.DefaultCreatedAt = exclusionDescCreatedAt.Default.(func() time.Time)
	// exclusionDescUpdatedAt is the schema descriptor for updated_at field.
	exclusionDescUpdatedAt := exclusionMixinFields0[1].Descriptor()
	// exclusion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	exclusion.DefaultUpdatedAt = exclusionDescUpdatedAt.Default.(func() time.Time)
	// exclusion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	exclusion.UpdateDefaultUpdatedAt = exclusionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// exclusionDescBrandName is the schema descriptor for brand_name field.
	exclusionDescBrandName := exclusionFields[2].Descriptor()
	// exclusion.BrandNameValidator is a validator for the "brand_name" field. It is called by the builders before save.
	exclusion.BrandNameValidator = exclusionDescBrandName.Validators[0].(func(string) error)
	saleeventMixin := schema.SaleEvent{}.Mixin()
	saleeventMixinFields0 := saleeventMixin[0].Fields()
	_ = saleeventMixinFields0
	saleeventFields := schema.SaleEvent{}.Fields()
	_ = saleeventFields
	// saleeventDescCreatedAt is the schema descriptor for created_at field.
	saleeventDescCreatedAt := saleeventMixinFields0[0].Descriptor()
	// saleevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	saleevent.DefaultCreatedAt = saleeventDescCreatedAt.Default.(func() time.Time)
	// saleeventDescUpdatedAt is the schema descriptor for updated_at field.
	saleeventDescUpdatedAt := saleeventMixinFields0[1].Descriptor()
	// saleevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	saleevent.DefaultUpdatedAt = saleeventDescUpdatedAt.Default.(func() time.Time)
	// saleevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	saleevent.UpdateDefaultUpdatedAt = saleeventDescUpdatedAt.UpdateDefault.(func() time.Time)
	// saleeventDescIsReturn is the schema descriptor for is_return field.
	saleeventDescIsReturn := saleeventFields[6].Descriptor()
	// saleevent.DefaultIsReturn holds the default value on creation for the is_return field.
	saleevent.DefaultIsReturn = saleeventDescIsReturn.Default.(bool)
}
