// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
	"gitlab.calendaria.team/services/platform-billing/ent/saleevent"
)

// SaleEventUpdate is the builder for updating SaleEvent entities.
type SaleEventUpdate struct {
	config
	hooks     []Hook
	mutation  *SaleEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SaleEventUpdate builder.
func (seu *SaleEventUpdate) Where(ps ...predicate.SaleEvent) *SaleEventUpdate {
	seu.mutation.Where(ps...)
	return seu
}

// SetUpdatedAt sets the "updated_at" field.
func (seu *SaleEventUpdate) SetUpdatedAt(t time.Time) *SaleEventUpdate {
	seu.mutation.SetUpdatedAt(t)
	return seu
}

// SetAmount sets the "amount" field.
func (seu *SaleEventUpdate) SetAmount(d decimal.Decimal) *SaleEventUpdate {
	seu.mutation.ResetAmount()
	seu.mutation.SetAmount(d)
	return seu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (seu *SaleEventUpdate) SetNillableAmount(d *decimal.Decimal) *SaleEventUpdate {
	if d != nil {
		seu.SetAmount(*d)
	}
	return seu
}

// AddAmount adds d to the "amount" field.
func (seu *SaleEventUpdate) AddAmount(d decimal.Decimal) *SaleEventUpdate {
	seu.mutation.AddAmount(d)
	return seu
}

// SetCompletedAt sets the "completed_at" field.
func (seu *SaleEventUpdate) SetCompletedAt(t time.Time) *SaleEventUpdate {
	seu.mutation.SetCompletedAt(t)
	return seu
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (seu *SaleEventUpdate) SetNillableCompletedAt(t *time.Time) *SaleEventUpdate {
	if t != nil {
		seu.SetCompletedAt(*t)
	}
	return seu
}

// SetIsReturn sets the "is_return" field.
func (seu *SaleEventUpdate) SetIsReturn(b bool) *SaleEventUpdate {
	seu.mutation.SetIsReturn(b)
	return seu
}

// SetNillableIsReturn sets the "is_return" field if the given value is not nil.
func (seu *SaleEventUpdate) SetNillableIsReturn(b *bool) *SaleEventUpdate {
	if b != nil {
		seu.SetIsReturn(*b)
	}
	return seu
}

// Mutation returns the SaleEventMutation object of the builder.
func (seu *SaleEventUpdate) Mutation() *SaleEventMutation {
	return seu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (seu *SaleEventUpdate) Save(ctx context.Context) (int, error) {
	seu.defaults()
	return withHooks(ctx, seu.sqlSave, seu.mutation, seu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seu *SaleEventUpdate) SaveX(ctx context.Context) int {
	affected, err := seu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (seu *SaleEventUpdate) Exec(ctx context.Context) error {
	_, err := seu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seu *SaleEventUpdate) ExecX(ctx context.Context) {
	if err := seu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (seu *SaleEventUpdate) defaults() {
	if _, ok := seu.mutation.UpdatedAt(); !ok {
		v := saleevent.UpdateDefaultUpdatedAt()
		seu.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (seu *SaleEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleEventUpdate {
	seu.modifiers = append(seu.modifiers, modifiers...)
	return seu
}

func (seu *SaleEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(saleevent.Table, saleevent.Columns, sqlgraph.NewFieldSpec(saleevent.FieldID, field.TypeInt64))
	if ps := seu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seu.mutation.UpdatedAt(); ok {
		_spec.SetField(saleevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := seu.mutation.Amount(); ok {
		_spec.SetField(saleevent.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := seu.mutation.AddedAmount(); ok {
		_spec.AddField(saleevent.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := seu.mutation.CompletedAt(); ok {
		_spec.SetField(saleevent.FieldCompletedAt, field.TypeTime, value)
	}
	if value, ok := seu.mutation.IsReturn(); ok {
		_spec.SetField(saleevent.FieldIsReturn, field.TypeBool, value)
	}
	_spec.AddModifiers(seu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, seu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saleevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	seu.mutation.done = true
	return n, nil
}

// SaleEventUpdateOne is the builder for updating a single SaleEvent entity.
type SaleEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SaleEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (seuo *SaleEventUpdateOne) SetUpdatedAt(t time.Time) *SaleEventUpdateOne {
	seuo.mutation.SetUpdatedAt(t)
	return seuo
}

// SetAmount sets the "amount" field.
func (seuo *SaleEventUpdateOne) SetAmount(d decimal.Decimal) *SaleEventUpdateOne {
	seuo.mutation.ResetAmount()
	seuo.mutation.SetAmount(d)
	return seuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (seuo *SaleEventUpdateOne) SetNillableAmount(d *decimal.Decimal) *SaleEventUpdateOne {
	if d != nil {
		seuo.SetAmount(*d)
	}
	return seuo
}

// AddAmount adds d to the "amount" field.
func (seuo *SaleEventUpdateOne) AddAmount(d decimal.Decimal) *SaleEventUpdateOne {
	seuo.mutation.AddAmount(d)
	return seuo
}

// SetCompletedAt sets the "completed_at" field.
func (seuo *SaleEventUpdateOne) SetCompletedAt(t time.Time) *SaleEventUpdateOne {
	seuo.mutation.SetCompletedAt(t)
	return seuo
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (seuo *SaleEventUpdateOne) SetNillableCompletedAt(t *time.Time) *SaleEventUpdateOne {
	if t != nil {
		seuo.SetCompletedAt(*t)
	}
	return seuo
}

// SetIsReturn sets the "is_return" field.
func (seuo *SaleEventUpdateOne) SetIsReturn(b bool) *SaleEventUpdateOne {
	seuo.mutation.SetIsReturn(b)
	return seuo
}

// SetNillableIsReturn sets the "is_return" field if the given value is not nil.
func (seuo *SaleEventUpdateOne) SetNillableIsReturn(b *bool) *SaleEventUpdateOne {
	if b != nil {
		seuo.SetIsReturn(*b)
	}
	return seuo
}

// Mutation returns the SaleEventMutation object of the builder.
func (seuo *SaleEventUpdateOne) Mutation() *SaleEventMutation {
	return seuo.mutation
}

// Where appends a list predicates to the SaleEventUpdate builder.
func (seuo *SaleEventUpdateOne) Where(ps ...predicate.SaleEvent) *SaleEventUpdateOne {
	seuo.mutation.Where(ps...)
	return seuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (seuo *SaleEventUpdateOne) Select(field string, fields ...string) *SaleEventUpdateOne {
	seuo.fields = append([]string{field}, fields...)
	return seuo
}

// Save executes the query and returns the updated SaleEvent entity.
func (seuo *SaleEventUpdateOne) Save(ctx context.Context) (*SaleEvent, error) {
	seuo.defaults()
	return withHooks(ctx, seuo.sqlSave, seuo.mutation, seuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (seuo *SaleEventUpdateOne) SaveX(ctx context.Context) *SaleEvent {
	node, err := seuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (seuo *SaleEventUpdateOne) Exec(ctx context.Context) error {
	_, err := seuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (seuo *SaleEventUpdateOne) ExecX(ctx context.Context) {
	if err := seuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (seuo *SaleEventUpdateOne) defaults() {
	if _, ok := seuo.mutation.UpdatedAt(); !ok {
		v := saleevent.UpdateDefaultUpdatedAt()
		seuo.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (seuo *SaleEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleEventUpdateOne {
	seuo.modifiers = append(seuo.modifiers, modifiers...)
	return seuo
}

func (seuo *SaleEventUpdateOne) sqlSave(ctx context.Context) (_node *SaleEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(saleevent.Table, saleevent.Columns, sqlgraph.NewFieldSpec(saleevent.FieldID, field.TypeInt64))
	id, ok := seuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SaleEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := seuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, saleevent.FieldID)
		for _, f := range fields {
			if !saleevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != saleevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := seuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := seuo.mutation.UpdatedAt(); ok {
		_spec.SetField(saleevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := seuo.mutation.Amount(); ok {
		_spec.SetField(saleevent.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := seuo.mutation.AddedAmount(); ok {
		_spec.AddField(saleevent.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := seuo.mutation.CompletedAt(); ok {
		_spec.SetField(saleevent.FieldCompletedAt, field.TypeTime, value)
	}
	if value, ok := seuo.mutation.IsReturn(); ok {
		_spec.SetField(saleevent.FieldIsReturn, field.TypeBool, value)
	}
	_spec.AddModifiers(seuo.modifiers...)
	_node = &SaleEvent{config: seuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, seuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saleevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	seuo.mutation.done = true
	return _node, nil
}
