// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/platform-billing/ent/saleevent"
)

// SaleEventCreate is the builder for creating a SaleEvent entity.
type SaleEventCreate struct {
	config
	mutation *SaleEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (sec *SaleEventCreate) SetCreatedAt(t time.Time) *SaleEventCreate {
	sec.mutation.SetCreatedAt(t)
	return sec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sec *SaleEventCreate) SetNillableCreatedAt(t *time.Time) *SaleEventCreate {
	if t != nil {
		sec.SetCreatedAt(*t)
	}
	return sec
}

// SetUpdatedAt sets the "updated_at" field.
func (sec *SaleEventCreate) SetUpdatedAt(t time.Time) *SaleEventCreate {
	sec.mutation.SetUpdatedAt(t)
	return sec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sec *SaleEventCreate) SetNillableUpdatedAt(t *time.Time) *SaleEventCreate {
	if t != nil {
		sec.SetUpdatedAt(*t)
	}
	return sec
}

// SetTenantID sets the "tenant_id" field.
func (sec *SaleEventCreate) SetTenantID(i int64) *SaleEventCreate {
	sec.mutation.SetTenantID(i)
	return sec
}

// SetSaleID sets the "sale_id" field.
func (sec *SaleEventCreate) SetSaleID(i int64) *SaleEventCreate {
	sec.mutation.SetSaleID(i)
	return sec
}

// SetProductID sets the "product_id" field.
func (sec *SaleEventCreate) SetProductID(i int64) *SaleEventCreate {
	sec.mutation.SetProductID(i)
	return sec
}

// SetAmount sets the "amount" field.
func (sec *SaleEventCreate) SetAmount(d decimal.Decimal) *SaleEventCreate {
	sec.mutation.SetAmount(d)
	return sec
}

// SetCompletedAt sets the "completed_at" field.
func (sec *SaleEventCreate) SetCompletedAt(t time.Time) *SaleEventCreate {
	sec.mutation.SetCompletedAt(t)
	return sec
}

// SetIsReturn sets the "is_return" field.
func (sec *SaleEventCreate) SetIsReturn(b bool) *SaleEventCreate {
	sec.mutation.SetIsReturn(b)
	return sec
}

// SetNillableIsReturn sets the "is_return" field if the given value is not nil.
func (sec *SaleEventCreate) SetNillableIsReturn(b *bool) *SaleEventCreate {
	if b != nil {
		sec.SetIsReturn(*b)
	}
	return sec
}

// SetID sets the "id" field.
func (sec *SaleEventCreate) SetID(i int64) *SaleEventCreate {
	sec.mutation.SetID(i)
	return sec
}

// Mutation returns the SaleEventMutation object of the builder.
func (sec *SaleEventCreate) Mutation() *SaleEventMutation {
	return sec.mutation
}

// Save creates the SaleEvent in the database.
func (sec *SaleEventCreate) Save(ctx context.Context) (*SaleEvent, error) {
	sec.defaults()
	return withHooks(ctx, sec.sqlSave, sec.mutation, sec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sec *SaleEventCreate) SaveX(ctx context.Context) *SaleEvent {
	v, err := sec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sec *SaleEventCreate) Exec(ctx context.Context) error {
	_, err := sec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sec *SaleEventCreate) ExecX(ctx context.Context) {
	if err := sec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sec *SaleEventCreate) defaults() {
	if _, ok := sec.mutation.CreatedAt(); !ok {
		v := saleevent.DefaultCreatedAt()
		sec.mutation.SetCreatedAt(v)
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		v := saleevent.DefaultUpdatedAt()
		sec.mutation.SetUpdatedAt(v)
	}
	if _, ok := sec.mutation.IsReturn(); !ok {
		v := saleevent.DefaultIsReturn
		sec.mutation.SetIsReturn(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sec *SaleEventCreate) check() error {
	if _, ok := sec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SaleEvent.created_at"`)}
	}
	if _, ok := sec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SaleEvent.updated_at"`)}
	}
	if _, ok := sec.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SaleEvent.tenant_id"`)}
	}
	if _, ok := sec.mutation.SaleID(); !ok {
		return &ValidationError{Name: "sale_id", err: errors.New(`ent: missing required field "SaleEvent.sale_id"`)}
	}
	if _, ok := sec.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "SaleEvent.product_id"`)}
	}
	if _, ok := sec.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "SaleEvent.amount"`)}
	}
	if _, ok := sec.mutation.CompletedAt(); !ok {
		return &ValidationError{Name: "completed_at", err: errors.New(`ent: missing required field "SaleEvent.completed_at"`)}
	}
	if _, ok := sec.mutation.IsReturn(); !ok {
		return &ValidationError{Name: "is_return", err: errors.New(`ent: missing required field "SaleEvent.is_return"`)}
	}
	return nil
}

func (sec *SaleEventCreate) sqlSave(ctx context.Context) (*SaleEvent, error) {
	if err := sec.check(); err != nil {
		return nil, err
	}
	_node, _spec := sec.createSpec()
	if err := sqlgraph.CreateNode(ctx, sec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sec.mutation.id = &_node.ID
	sec.mutation.done = true
	return _node, nil
}

func (sec *SaleEventCreate) createSpec() (*SaleEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SaleEvent{config: sec.config}
		_spec = sqlgraph.NewCreateSpec(saleevent.Table, sqlgraph.NewFieldSpec(saleevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = sec.conflict
	if id, ok := sec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sec.mutation.CreatedAt(); ok {
		_spec.SetField(saleevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sec.mutation.UpdatedAt(); ok {
		_spec.SetField(saleevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sec.mutation.TenantID(); ok {
		_spec.SetField(saleevent.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := sec.mutation.SaleID(); ok {
		_spec.SetField(saleevent.FieldSaleID, field.TypeInt64, value)
		_node.SaleID = value
	}
	if value, ok := sec.mutation.ProductID(); ok {
		_spec.SetField(saleevent.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := sec.mutation.Amount(); ok {
		_spec.SetField(saleevent.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := sec.mutation.CompletedAt(); ok {
		_spec.SetField(saleevent.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := sec.mutation.IsReturn(); ok {
		_spec.SetField(saleevent.FieldIsReturn, field.TypeBool, value)
		_node.IsReturn = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (sec *SaleEventCreate) OnConflict(opts ...sql.ConflictOption) *SaleEventUpsertOne {
	sec.conflict = opts
	return &SaleEventUpsertOne{
		create: sec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sec *SaleEventCreate) OnConflictColumns(columns ...string) *SaleEventUpsertOne {
	sec.conflict = append(sec.conflict, sql.ConflictColumns(columns...))
	return &SaleEventUpsertOne{
		create: sec,
	}
}

type (
	// SaleEventUpsertOne is the builder for "upsert"-ing
	//  one SaleEvent node.
	SaleEventUpsertOne struct {
		create *SaleEventCreate
	}

	// SaleEventUpsert is the "OnConflict" setter.
	SaleEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleEventUpsert) SetUpdatedAt(v time.Time) *SaleEventUpsert {
	u.Set(saleevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleEventUpsert) UpdateUpdatedAt() *SaleEventUpsert {
	u.SetExcluded(saleevent.FieldUpdatedAt)
	return u
}

// SetAmount sets the "amount" field.
func (u *SaleEventUpsert) SetAmount(v decimal.Decimal) *SaleEventUpsert {
	u.Set(saleevent.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SaleEventUpsert) UpdateAmount() *SaleEventUpsert {
	u.SetExcluded(saleevent.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *SaleEventUpsert) AddAmount(v decimal.Decimal) *SaleEventUpsert {
	u.Add(saleevent.FieldAmount, v)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *SaleEventUpsert) SetCompletedAt(v time.Time) *SaleEventUpsert {
	u.Set(saleevent.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SaleEventUpsert) UpdateCompletedAt() *SaleEventUpsert {
	u.SetExcluded(saleevent.FieldCompletedAt)
	return u
}

// SetIsReturn sets the "is_return" field.
func (u *SaleEventUpsert) SetIsReturn(v bool) *SaleEventUpsert {
	u.Set(saleevent.FieldIsReturn, v)
	return u
}

// UpdateIsReturn sets the "is_return" field to the value that was provided on create.
func (u *SaleEventUpsert) UpdateIsReturn() *SaleEventUpsert {
	u.SetExcluded(saleevent.FieldIsReturn)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(saleevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleEventUpsertOne) UpdateNewValues() *SaleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(saleevent.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(saleevent.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(saleevent.FieldTenantID)
		}
		if _, exists := u.create.mutation.SaleID(); exists {
			s.SetIgnore(saleevent.FieldSaleID)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(saleevent.FieldProductID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SaleEventUpsertOne) Ignore() *SaleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleEventUpsertOne) DoNothing() *SaleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleEventCreate.OnConflict
// documentation for more info.
func (u *SaleEventUpsertOne) Update(set func(*SaleEventUpsert)) *SaleEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleEventUpsertOne) SetUpdatedAt(v time.Time) *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleEventUpsertOne) UpdateUpdatedAt() *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAmount sets the "amount" field.
func (u *SaleEventUpsertOne) SetAmount(v decimal.Decimal) *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SaleEventUpsertOne) AddAmount(v decimal.Decimal) *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SaleEventUpsertOne) UpdateAmount() *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateAmount()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SaleEventUpsertOne) SetCompletedAt(v time.Time) *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SaleEventUpsertOne) UpdateCompletedAt() *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateCompletedAt()
	})
}

// SetIsReturn sets the "is_return" field.
func (u *SaleEventUpsertOne) SetIsReturn(v bool) *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetIsReturn(v)
	})
}

// UpdateIsReturn sets the "is_return" field to the value that was provided on create.
func (u *SaleEventUpsertOne) UpdateIsReturn() *SaleEventUpsertOne {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateIsReturn()
	})
}

// Exec executes the query.
func (u *SaleEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SaleEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SaleEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SaleEventCreateBulk is the builder for creating many SaleEvent entities in bulk.
type SaleEventCreateBulk struct {
	config
	err      error
	builders []*SaleEventCreate
	conflict []sql.ConflictOption
}

// Save creates the SaleEvent entities in the database.
func (secb *SaleEventCreateBulk) Save(ctx context.Context) ([]*SaleEvent, error) {
	if secb.err != nil {
		return nil, secb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(secb.builders))
	nodes := make([]*SaleEvent, len(secb.builders))
	mutators := make([]Mutator, len(secb.builders))
	for i := range secb.builders {
		func(i int, root context.Context) {
			builder := secb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, secb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = secb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, secb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, secb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (secb *SaleEventCreateBulk) SaveX(ctx context.Context) []*SaleEvent {
	v, err := secb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (secb *SaleEventCreateBulk) Exec(ctx context.Context) error {
	_, err := secb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (secb *SaleEventCreateBulk) ExecX(ctx context.Context) {
	if err := secb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (secb *SaleEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *SaleEventUpsertBulk {
	secb.conflict = opts
	return &SaleEventUpsertBulk{
		create: secb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (secb *SaleEventCreateBulk) OnConflictColumns(columns ...string) *SaleEventUpsertBulk {
	secb.conflict = append(secb.conflict, sql.ConflictColumns(columns...))
	return &SaleEventUpsertBulk{
		create: secb,
	}
}

// SaleEventUpsertBulk is the builder for "upsert"-ing
// a bulk of SaleEvent nodes.
type SaleEventUpsertBulk struct {
	create *SaleEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(saleevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleEventUpsertBulk) UpdateNewValues() *SaleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(saleevent.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(saleevent.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(saleevent.FieldTenantID)
			}
			if _, exists := b.mutation.SaleID(); exists {
				s.SetIgnore(saleevent.FieldSaleID)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(saleevent.FieldProductID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SaleEventUpsertBulk) Ignore() *SaleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleEventUpsertBulk) DoNothing() *SaleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleEventCreateBulk.OnConflict
// documentation for more info.
func (u *SaleEventUpsertBulk) Update(set func(*SaleEventUpsert)) *SaleEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleEventUpsertBulk) SetUpdatedAt(v time.Time) *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleEventUpsertBulk) UpdateUpdatedAt() *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAmount sets the "amount" field.
func (u *SaleEventUpsertBulk) SetAmount(v decimal.Decimal) *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *SaleEventUpsertBulk) AddAmount(v decimal.Decimal) *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *SaleEventUpsertBulk) UpdateAmount() *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateAmount()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SaleEventUpsertBulk) SetCompletedAt(v time.Time) *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SaleEventUpsertBulk) UpdateCompletedAt() *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateCompletedAt()
	})
}

// SetIsReturn sets the "is_return" field.
func (u *SaleEventUpsertBulk) SetIsReturn(v bool) *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.SetIsReturn(v)
	})
}

// UpdateIsReturn sets the "is_return" field to the value that was provided on create.
func (u *SaleEventUpsertBulk) UpdateIsReturn() *SaleEventUpsertBulk {
	return u.Update(func(s *SaleEventUpsert) {
		s.UpdateIsReturn()
	})
}

// Exec executes the query.
func (u *SaleEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SaleEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
