// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/platform-billing/ent"
	"gitlab.calendaria.team/services/platform-billing/ent/commission"
	"gitlab.calendaria.team/services/platform-billing/ent/exclusion"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
	"gitlab.calendaria.team/services/platform-billing/ent/saleevent"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The CommissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type CommissionFunc func(context.Context, *ent.CommissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CommissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CommissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CommissionQuery", q)
}

// The TraverseCommission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCommission func(context.Context, *ent.CommissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCommission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCommission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CommissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CommissionQuery", q)
}

// The ExclusionFunc type is an adapter to allow the use of ordinary function as a Querier.
type ExclusionFunc func(context.Context, *ent.ExclusionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ExclusionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ExclusionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ExclusionQuery", q)
}

// The TraverseExclusion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseExclusion func(context.Context, *ent.ExclusionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseExclusion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseExclusion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ExclusionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ExclusionQuery", q)
}

// The SaleEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type SaleEventFunc func(context.Context, *ent.SaleEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SaleEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SaleEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SaleEventQuery", q)
}

// The TraverseSaleEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSaleEvent func(context.Context, *ent.SaleEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSaleEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSaleEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SaleEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SaleEventQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.CommissionQuery:
		return &query[*ent.CommissionQuery, predicate.Commission, commission.OrderOption]{typ: ent.TypeCommission, tq: q}, nil
	case *ent.ExclusionQuery:
		return &query[*ent.ExclusionQuery, predicate.Exclusion, exclusion.OrderOption]{typ: ent.TypeExclusion, tq: q}, nil
	case *ent.SaleEventQuery:
		return &query[*ent.SaleEventQuery, predicate.SaleEvent, saleevent.OrderOption]{typ: ent.TypeSaleEvent, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
