// Code generated by ent, DO NOT EDIT.

package commission

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/platform-billing/ent/enum"
)

const (
	// Label holds the string label denoting the commission type in the database.
	Label = "commission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldGmv holds the string denoting the gmv field in the database.
	FieldGmv = "gmv"
	// FieldExcludedAmount holds the string denoting the excluded_amount field in the database.
	FieldExcludedAmount = "excluded_amount"
	// FieldTaxableAmount holds the string denoting the taxable_amount field in the database.
	FieldTaxableAmount = "taxable_amount"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldCommission holds the string denoting the commission field in the database.
	FieldCommission = "commission"
	// FieldManagerShareRate holds the string denoting the manager_share_rate field in the database.
	FieldManagerShareRate = "manager_share_rate"
	// FieldManagerShare holds the string denoting the manager_share field in the database.
	FieldManagerShare = "manager_share"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// Table holds the table name of the commission in the database.
	Table = "commissions"
)

// Columns holds all SQL columns for commission fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldGmv,
	FieldExcludedAmount,
	FieldTaxableAmount,
	FieldRate,
	FieldCommission,
	FieldManagerShareRate,
	FieldManagerShare,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

const DefaultStatus enum.CommissionStatus = "PENDING"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enum.CommissionStatus) error {
	switch s {
	case "PENDING", "CHARGED", "FAILED":
		return nil
	default:
		return fmt.Errorf("commission: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Commission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByGmv orders the results by the gmv field.
func ByGmv(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGmv, opts...).ToFunc()
}

// ByExcludedAmount orders the results by the excluded_amount field.
func ByExcludedAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcludedAmount, opts...).ToFunc()
}

// ByTaxableAmount orders the results by the taxable_amount field.
func ByTaxableAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxableAmount, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByCommission orders the results by the commission field.
func ByCommission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommission, opts...).ToFunc()
}

// ByManagerShareRate orders the results by the manager_share_rate field.
func ByManagerShareRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagerShareRate, opts...).ToFunc()
}

// ByManagerShare orders the results by the manager_share field.
func ByManagerShare(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagerShare, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}
