// Code generated by ent, DO NOT EDIT.

package commission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/platform-billing/ent/enum"
	"gitlab.calendaria.team/services/platform-billing/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldTenantID, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldPeriodEnd, v))
}

// Gmv applies equality check predicate on the "gmv" field. It's identical to GmvEQ.
func Gmv(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldGmv, v))
}

// ExcludedAmount applies equality check predicate on the "excluded_amount" field. It's identical to ExcludedAmountEQ.
func ExcludedAmount(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldExcludedAmount, v))
}

// TaxableAmount applies equality check predicate on the "taxable_amount" field. It's identical to TaxableAmountEQ.
func TaxableAmount(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldTaxableAmount, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldRate, v))
}

// Commission applies equality check predicate on the "commission" field. It's identical to CommissionEQ.
func Commission(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldCommission, v))
}

// ManagerShareRate applies equality check predicate on the "manager_share_rate" field. It's identical to ManagerShareRateEQ.
func ManagerShareRate(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldManagerShareRate, v))
}

// ManagerShare applies equality check predicate on the "manager_share" field. It's identical to ManagerShareEQ.
func ManagerShare(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldManagerShare, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldTenantID, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldPeriodEnd, v))
}

// GmvEQ applies the EQ predicate on the "gmv" field.
func GmvEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldGmv, v))
}

// GmvNEQ applies the NEQ predicate on the "gmv" field.
func GmvNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldGmv, v))
}

// GmvIn applies the In predicate on the "gmv" field.
func GmvIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldGmv, vs...))
}

// GmvNotIn applies the NotIn predicate on the "gmv" field.
func GmvNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldGmv, vs...))
}

// GmvGT applies the GT predicate on the "gmv" field.
func GmvGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldGmv, v))
}

// GmvGTE applies the GTE predicate on the "gmv" field.
func GmvGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldGmv, v))
}

// GmvLT applies the LT predicate on the "gmv" field.
func GmvLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldGmv, v))
}

// GmvLTE applies the LTE predicate on the "gmv" field.
func GmvLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldGmv, v))
}

// GmvIsNil applies the IsNil predicate on the "gmv" field.
func GmvIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldGmv))
}

// GmvNotNil applies the NotNil predicate on the "gmv" field.
func GmvNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldGmv))
}

// ExcludedAmountEQ applies the EQ predicate on the "excluded_amount" field.
func ExcludedAmountEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldExcludedAmount, v))
}

// ExcludedAmountNEQ applies the NEQ predicate on the "excluded_amount" field.
func ExcludedAmountNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldExcludedAmount, v))
}

// ExcludedAmountIn applies the In predicate on the "excluded_amount" field.
func ExcludedAmountIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldExcludedAmount, vs...))
}

// ExcludedAmountNotIn applies the NotIn predicate on the "excluded_amount" field.
func ExcludedAmountNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldExcludedAmount, vs...))
}

// ExcludedAmountGT applies the GT predicate on the "excluded_amount" field.
func ExcludedAmountGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldExcludedAmount, v))
}

// ExcludedAmountGTE applies the GTE predicate on the "excluded_amount" field.
func ExcludedAmountGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldExcludedAmount, v))
}

// ExcludedAmountLT applies the LT predicate on the "excluded_amount" field.
func ExcludedAmountLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldExcludedAmount, v))
}

// ExcludedAmountLTE applies the LTE predicate on the "excluded_amount" field.
func ExcludedAmountLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldExcludedAmount, v))
}

// ExcludedAmountIsNil applies the IsNil predicate on the "excluded_amount" field.
func ExcludedAmountIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldExcludedAmount))
}

// ExcludedAmountNotNil applies the NotNil predicate on the "excluded_amount" field.
func ExcludedAmountNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldExcludedAmount))
}

// TaxableAmountEQ applies the EQ predicate on the "taxable_amount" field.
func TaxableAmountEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldTaxableAmount, v))
}

// TaxableAmountNEQ applies the NEQ predicate on the "taxable_amount" field.
func TaxableAmountNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldTaxableAmount, v))
}

// TaxableAmountIn applies the In predicate on the "taxable_amount" field.
func TaxableAmountIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldTaxableAmount, vs...))
}

// TaxableAmountNotIn applies the NotIn predicate on the "taxable_amount" field.
func TaxableAmountNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldTaxableAmount, vs...))
}

// TaxableAmountGT applies the GT predicate on the "taxable_amount" field.
func TaxableAmountGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldTaxableAmount, v))
}

// TaxableAmountGTE applies the GTE predicate on the "taxable_amount" field.
func TaxableAmountGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldTaxableAmount, v))
}

// TaxableAmountLT applies the LT predicate on the "taxable_amount" field.
func TaxableAmountLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldTaxableAmount, v))
}

// TaxableAmountLTE applies the LTE predicate on the "taxable_amount" field.
func TaxableAmountLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldTaxableAmount, v))
}

// TaxableAmountIsNil applies the IsNil predicate on the "taxable_amount" field.
func TaxableAmountIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldTaxableAmount))
}

// TaxableAmountNotNil applies the NotNil predicate on the "taxable_amount" field.
func TaxableAmountNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldTaxableAmount))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldRate, v))
}

// RateIsNil applies the IsNil predicate on the "rate" field.
func RateIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldRate))
}

// RateNotNil applies the NotNil predicate on the "rate" field.
func RateNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldRate))
}

// CommissionEQ applies the EQ predicate on the "commission" field.
func CommissionEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldCommission, v))
}

// CommissionNEQ applies the NEQ predicate on the "commission" field.
func CommissionNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldCommission, v))
}

// CommissionIn applies the In predicate on the "commission" field.
func CommissionIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldCommission, vs...))
}

// CommissionNotIn applies the NotIn predicate on the "commission" field.
func CommissionNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldCommission, vs...))
}

// CommissionGT applies the GT predicate on the "commission" field.
func CommissionGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldCommission, v))
}

// CommissionGTE applies the GTE predicate on the "commission" field.
func CommissionGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldCommission, v))
}

// CommissionLT applies the LT predicate on the "commission" field.
func CommissionLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldCommission, v))
}

// CommissionLTE applies the LTE predicate on the "commission" field.
func CommissionLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldCommission, v))
}

// CommissionIsNil applies the IsNil predicate on the "commission" field.
func CommissionIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldCommission))
}

// CommissionNotNil applies the NotNil predicate on the "commission" field.
func CommissionNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldCommission))
}

// ManagerShareRateEQ applies the EQ predicate on the "manager_share_rate" field.
func ManagerShareRateEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldManagerShareRate, v))
}

// ManagerShareRateNEQ applies the NEQ predicate on the "manager_share_rate" field.
func ManagerShareRateNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldManagerShareRate, v))
}

// ManagerShareRateIn applies the In predicate on the "manager_share_rate" field.
func ManagerShareRateIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldManagerShareRate, vs...))
}

// ManagerShareRateNotIn applies the NotIn predicate on the "manager_share_rate" field.
func ManagerShareRateNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldManagerShareRate, vs...))
}

// ManagerShareRateGT applies the GT predicate on the "manager_share_rate" field.
func ManagerShareRateGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldManagerShareRate, v))
}

// ManagerShareRateGTE applies the GTE predicate on the "manager_share_rate" field.
func ManagerShareRateGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldManagerShareRate, v))
}

// ManagerShareRateLT applies the LT predicate on the "manager_share_rate" field.
func ManagerShareRateLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldManagerShareRate, v))
}

// ManagerShareRateLTE applies the LTE predicate on the "manager_share_rate" field.
func ManagerShareRateLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldManagerShareRate, v))
}

// ManagerShareRateIsNil applies the IsNil predicate on the "manager_share_rate" field.
func ManagerShareRateIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldManagerShareRate))
}

// ManagerShareRateNotNil applies the NotNil predicate on the "manager_share_rate" field.
func ManagerShareRateNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldManagerShareRate))
}

// ManagerShareEQ applies the EQ predicate on the "manager_share" field.
func ManagerShareEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldEQ(FieldManagerShare, v))
}

// ManagerShareNEQ applies the NEQ predicate on the "manager_share" field.
func ManagerShareNEQ(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNEQ(FieldManagerShare, v))
}

// ManagerShareIn applies the In predicate on the "manager_share" field.
func ManagerShareIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldIn(FieldManagerShare, vs...))
}

// ManagerShareNotIn applies the NotIn predicate on the "manager_share" field.
func ManagerShareNotIn(vs ...decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldNotIn(FieldManagerShare, vs...))
}

// ManagerShareGT applies the GT predicate on the "manager_share" field.
func ManagerShareGT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGT(FieldManagerShare, v))
}

// ManagerShareGTE applies the GTE predicate on the "manager_share" field.
func ManagerShareGTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldGTE(FieldManagerShare, v))
}

// ManagerShareLT applies the LT predicate on the "manager_share" field.
func ManagerShareLT(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLT(FieldManagerShare, v))
}

// ManagerShareLTE applies the LTE predicate on the "manager_share" field.
func ManagerShareLTE(v decimal.Decimal) predicate.Commission {
	return predicate.Commission(sql.FieldLTE(FieldManagerShare, v))
}

// ManagerShareIsNil applies the IsNil predicate on the "manager_share" field.
func ManagerShareIsNil() predicate.Commission {
	return predicate.Commission(sql.FieldIsNull(FieldManagerShare))
}

// ManagerShareNotNil applies the NotNil predicate on the "manager_share" field.
func ManagerShareNotNil() predicate.Commission {
	return predicate.Commission(sql.FieldNotNull(FieldManagerShare))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enum.CommissionStatus) predicate.Commission {
	vc := v
	return predicate.Commission(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enum.CommissionStatus) predicate.Commission {
	vc := v
	return predicate.Commission(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enum.CommissionStatus) predicate.Commission {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Commission(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enum.CommissionStatus) predicate.Commission {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Commission(sql.FieldNotIn(FieldStatus, v...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Commission) predicate.Commission {
	return predicate.Commission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Commission) predicate.Commission {
	return predicate.Commission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Commission) predicate.Commission {
	return predicate.Commission(sql.NotPredicates(p))
}
