// Code generated by ent, DO NOT EDIT.

package saleevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/platform-billing/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldTenantID, v))
}

// SaleID applies equality check predicate on the "sale_id" field. It's identical to SaleIDEQ.
func SaleID(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldSaleID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldProductID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldAmount, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldCompletedAt, v))
}

// IsReturn applies equality check predicate on the "is_return" field. It's identical to IsReturnEQ.
func IsReturn(v bool) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldIsReturn, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldTenantID, v))
}

// SaleIDEQ applies the EQ predicate on the "sale_id" field.
func SaleIDEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldSaleID, v))
}

// SaleIDNEQ applies the NEQ predicate on the "sale_id" field.
func SaleIDNEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldSaleID, v))
}

// SaleIDIn applies the In predicate on the "sale_id" field.
func SaleIDIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldSaleID, vs...))
}

// SaleIDNotIn applies the NotIn predicate on the "sale_id" field.
func SaleIDNotIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldSaleID, vs...))
}

// SaleIDGT applies the GT predicate on the "sale_id" field.
func SaleIDGT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldSaleID, v))
}

// SaleIDGTE applies the GTE predicate on the "sale_id" field.
func SaleIDGTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldSaleID, v))
}

// SaleIDLT applies the LT predicate on the "sale_id" field.
func SaleIDLT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldSaleID, v))
}

// SaleIDLTE applies the LTE predicate on the "sale_id" field.
func SaleIDLTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldSaleID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldProductID, vs...))
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldProductID, v))
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldProductID, v))
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldProductID, v))
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int64) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldProductID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldAmount, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldLTE(FieldCompletedAt, v))
}

// IsReturnEQ applies the EQ predicate on the "is_return" field.
func IsReturnEQ(v bool) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldEQ(FieldIsReturn, v))
}

// IsReturnNEQ applies the NEQ predicate on the "is_return" field.
func IsReturnNEQ(v bool) predicate.SaleEvent {
	return predicate.SaleEvent(sql.FieldNEQ(FieldIsReturn, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SaleEvent) predicate.SaleEvent {
	return predicate.SaleEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SaleEvent) predicate.SaleEvent {
	return predicate.SaleEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SaleEvent) predicate.SaleEvent {
	return predicate.SaleEvent(sql.NotPredicates(p))
}
