// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/platform_billing/v1/models.proto

package platform_billing_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Commission struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PeriodStart      string                 `protobuf:"bytes,3,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd        string                 `protobuf:"bytes,4,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Gmv              string                 `protobuf:"bytes,5,opt,name=gmv,proto3" json:"gmv,omitempty"`
	ExcludedAmount   string                 `protobuf:"bytes,6,opt,name=excluded_amount,json=excludedAmount,proto3" json:"excluded_amount,omitempty"`
	TaxableAmount    string                 `protobuf:"bytes,7,opt,name=taxable_amount,json=taxableAmount,proto3" json:"taxable_amount,omitempty"`
	Rate             string                 `protobuf:"bytes,8,opt,name=rate,proto3" json:"rate,omitempty"`
	Commission       string                 `protobuf:"bytes,9,opt,name=commission,proto3" json:"commission,omitempty"`
	Status           string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ManagerShareRate string                 `protobuf:"bytes,12,opt,name=manager_share_rate,json=managerShareRate,proto3" json:"manager_share_rate,omitempty"`
	ManagerShare     string                 `protobuf:"bytes,13,opt,name=manager_share,json=managerShare,proto3" json:"manager_share,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Commission) Reset() {
	*x = Commission{}
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commission) ProtoMessage() {}

func (x *Commission) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commission.ProtoReflect.Descriptor instead.
func (*Commission) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Commission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Commission) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Commission) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *Commission) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *Commission) GetGmv() string {
	if x != nil {
		return x.Gmv
	}
	return ""
}

func (x *Commission) GetExcludedAmount() string {
	if x != nil {
		return x.ExcludedAmount
	}
	return ""
}

func (x *Commission) GetTaxableAmount() string {
	if x != nil {
		return x.TaxableAmount
	}
	return ""
}

func (x *Commission) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *Commission) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *Commission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Commission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Commission) GetManagerShareRate() string {
	if x != nil {
		return x.ManagerShareRate
	}
	return ""
}

func (x *Commission) GetManagerShare() string {
	if x != nil {
		return x.ManagerShare
	}
	return ""
}

type Exclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	BrandName     string                 `protobuf:"bytes,3,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	SkuIds        []int64                `protobuf:"varint,4,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Exclusion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exclusion) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Exclusion) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *Exclusion) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

func (x *Exclusion) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Exclusion) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Exclusion) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Exclusion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BillingReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PeriodStart    string                 `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd      string                 `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	TotalGmv       string                 `protobuf:"bytes,4,opt,name=total_gmv,json=totalGmv,proto3" json:"total_gmv,omitempty"`
	ExcludedAmount string                 `protobuf:"bytes,5,opt,name=excluded_amount,json=excludedAmount,proto3" json:"excluded_amount,omitempty"`
	TaxableAmount  string                 `protobuf:"bytes,6,opt,name=taxable_amount,json=taxableAmount,proto3" json:"taxable_amount,omitempty"`
	Rate           string                 `protobuf:"bytes,7,opt,name=rate,proto3" json:"rate,omitempty"`
	Commission     string                 `protobuf:"bytes,8,opt,name=commission,proto3" json:"commission,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BillingReport) Reset() {
	*x = BillingReport{}
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingReport) ProtoMessage() {}

func (x *BillingReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingReport.ProtoReflect.Descriptor instead.
func (*BillingReport) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *BillingReport) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *BillingReport) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *BillingReport) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *BillingReport) GetTotalGmv() string {
	if x != nil {
		return x.TotalGmv
	}
	return ""
}

func (x *BillingReport) GetExcludedAmount() string {
	if x != nil {
		return x.ExcludedAmount
	}
	return ""
}

func (x *BillingReport) GetTaxableAmount() string {
	if x != nil {
		return x.TaxableAmount
	}
	return ""
}

func (x *BillingReport) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

func (x *BillingReport) GetCommission() string {
	if x != nil {
		return x.Commission
	}
	return ""
}

func (x *BillingReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_platform_billing_v1_models_proto protoreflect.FileDescriptor

const file_api_platform_billing_v1_models_proto_rawDesc = "" +
	"\n" +
	"$api/platform_billing/v1/models.proto\x12\x13platform_billing.v1\"\x9b\x03\n" +
	"\n" +
	"Commission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12!\n" +
	"\fperiod_start\x18\x03 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x04 \x01(\tR\tperiodEnd\x12\x10\n" +
	"\x03gmv\x18\x05 \x01(\tR\x03gmv\x12'\n" +
	"\x0fexcluded_amount\x18\x06 \x01(\tR\x0eexcludedAmount\x12%\n" +
	"\x0etaxable_amount\x18\a \x01(\tR\rtaxableAmount\x12\x12\n" +
	"\x04rate\x18\b \x01(\tR\x04rate\x12\x1e\n" +
	"\n" +
	"commission\x18\t \x01(\tR\n" +
	"commission\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12,\n" +
	"\x12manager_share_rate\x18\f \x01(\tR\x10managerShareRate\x12#\n" +
	"\rmanager_share\x18\r \x01(\tR\fmanagerShare\"\xe8\x01\n" +
	"\tExclusion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x03 \x01(\tR\tbrandName\x12\x17\n" +
	"\asku_ids\x18\x04 \x03(\x03R\x06skuIds\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\x03R\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xa7\x02\n" +
	"\rBillingReport\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12!\n" +
	"\fperiod_start\x18\x02 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x03 \x01(\tR\tperiodEnd\x12\x1b\n" +
	"\ttotal_gmv\x18\x04 \x01(\tR\btotalGmv\x12'\n" +
	"\x0fexcluded_amount\x18\x05 \x01(\tR\x0eexcludedAmount\x12%\n" +
	"\x0etaxable_amount\x18\x06 \x01(\tR\rtaxableAmount\x12\x12\n" +
	"\x04rate\x18\a \x01(\tR\x04rate\x12\x1e\n" +
	"\n" +
	"commission\x18\b \x01(\tR\n" +
	"commission\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06statusBTZRgithub.com/makesalekz/platform-billing/api/platform_billing/v1;platform_billing_v1b\x06proto3"

var (
	file_api_platform_billing_v1_models_proto_rawDescOnce sync.Once
	file_api_platform_billing_v1_models_proto_rawDescData []byte
)

func file_api_platform_billing_v1_models_proto_rawDescGZIP() []byte {
	file_api_platform_billing_v1_models_proto_rawDescOnce.Do(func() {
		file_api_platform_billing_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_platform_billing_v1_models_proto_rawDesc), len(file_api_platform_billing_v1_models_proto_rawDesc)))
	})
	return file_api_platform_billing_v1_models_proto_rawDescData
}

var file_api_platform_billing_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_platform_billing_v1_models_proto_goTypes = []any{
	(*Commission)(nil),    // 0: platform_billing.v1.Commission
	(*Exclusion)(nil),     // 1: platform_billing.v1.Exclusion
	(*BillingReport)(nil), // 2: platform_billing.v1.BillingReport
}
var file_api_platform_billing_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_platform_billing_v1_models_proto_init() }
func file_api_platform_billing_v1_models_proto_init() {
	if File_api_platform_billing_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_platform_billing_v1_models_proto_rawDesc), len(file_api_platform_billing_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_platform_billing_v1_models_proto_goTypes,
		DependencyIndexes: file_api_platform_billing_v1_models_proto_depIdxs,
		MessageInfos:      file_api_platform_billing_v1_models_proto_msgTypes,
	}.Build()
	File_api_platform_billing_v1_models_proto = out.File
	file_api_platform_billing_v1_models_proto_goTypes = nil
	file_api_platform_billing_v1_models_proto_depIdxs = nil
}
