// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/platform_billing/v1/platform_billing.proto

package platform_billing_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExclusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandName     string                 `protobuf:"bytes,1,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	SkuIds        []int64                `protobuf:"varint,2,rep,packed,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExclusionRequest) Reset() {
	*x = CreateExclusionRequest{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExclusionRequest) ProtoMessage() {}

func (x *CreateExclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExclusionRequest.ProtoReflect.Descriptor instead.
func (*CreateExclusionRequest) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExclusionRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *CreateExclusionRequest) GetSkuIds() []int64 {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

func (x *CreateExclusionRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateExclusionRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateExclusionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exclusion     *Exclusion             `protobuf:"bytes,1,opt,name=exclusion,proto3" json:"exclusion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExclusionReply) Reset() {
	*x = CreateExclusionReply{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExclusionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExclusionReply) ProtoMessage() {}

func (x *CreateExclusionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExclusionReply.ProtoReflect.Descriptor instead.
func (*CreateExclusionReply) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExclusionReply) GetExclusion() *Exclusion {
	if x != nil {
		return x.Exclusion
	}
	return nil
}

type ListExclusionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExclusionsRequest) Reset() {
	*x = ListExclusionsRequest{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExclusionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExclusionsRequest) ProtoMessage() {}

func (x *ListExclusionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExclusionsRequest.ProtoReflect.Descriptor instead.
func (*ListExclusionsRequest) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{2}
}

type ListExclusionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Exclusion           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExclusionsReply) Reset() {
	*x = ListExclusionsReply{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExclusionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExclusionsReply) ProtoMessage() {}

func (x *ListExclusionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExclusionsReply.ProtoReflect.Descriptor instead.
func (*ListExclusionsReply) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ListExclusionsReply) GetItems() []*Exclusion {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteExclusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExclusionRequest) Reset() {
	*x = DeleteExclusionRequest{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExclusionRequest) ProtoMessage() {}

func (x *DeleteExclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExclusionRequest.ProtoReflect.Descriptor instead.
func (*DeleteExclusionRequest) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteExclusionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteExclusionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExclusionReply) Reset() {
	*x = DeleteExclusionReply{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExclusionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExclusionReply) ProtoMessage() {}

func (x *DeleteExclusionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExclusionReply.ProtoReflect.Descriptor instead.
func (*DeleteExclusionReply) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{5}
}

type ClosePeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodEnd     string                 `protobuf:"bytes,1,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePeriodRequest) Reset() {
	*x = ClosePeriodRequest{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePeriodRequest) ProtoMessage() {}

func (x *ClosePeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePeriodRequest.ProtoReflect.Descriptor instead.
func (*ClosePeriodRequest) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ClosePeriodRequest) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

type ClosePeriodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClosedCount   int32                  `protobuf:"varint,1,opt,name=closed_count,json=closedCount,proto3" json:"closed_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClosePeriodReply) Reset() {
	*x = ClosePeriodReply{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClosePeriodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClosePeriodReply) ProtoMessage() {}

func (x *ClosePeriodReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClosePeriodReply.ProtoReflect.Descriptor instead.
func (*ClosePeriodReply) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{7}
}

func (x *ClosePeriodReply) GetClosedCount() int32 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

func (x *ClosePeriodReply) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type GetBillingReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PeriodStart   string                 `protobuf:"bytes,2,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     string                 `protobuf:"bytes,3,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingReportRequest) Reset() {
	*x = GetBillingReportRequest{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingReportRequest) ProtoMessage() {}

func (x *GetBillingReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingReportRequest.ProtoReflect.Descriptor instead.
func (*GetBillingReportRequest) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{8}
}

func (x *GetBillingReportRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *GetBillingReportRequest) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *GetBillingReportRequest) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

type GetBillingReportReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *BillingReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingReportReply) Reset() {
	*x = GetBillingReportReply{}
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingReportReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingReportReply) ProtoMessage() {}

func (x *GetBillingReportReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_platform_billing_v1_platform_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingReportReply.ProtoReflect.Descriptor instead.
func (*GetBillingReportReply) Descriptor() ([]byte, []int) {
	return file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetBillingReportReply) GetReport() *BillingReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_api_platform_billing_v1_platform_billing_proto protoreflect.FileDescriptor

const file_api_platform_billing_v1_platform_billing_proto_rawDesc = "" +
	"\n" +
	".api/platform_billing/v1/platform_billing.proto\x12\x13platform_billing.v1\x1a$api/platform_billing/v1/models.proto\"\x8a\x01\n" +
	"\x16CreateExclusionRequest\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x01 \x01(\tR\tbrandName\x12\x17\n" +
	"\asku_ids\x18\x02 \x03(\x03R\x06skuIds\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"T\n" +
	"\x14CreateExclusionReply\x12<\n" +
	"\texclusion\x18\x01 \x01(\v2\x1e.platform_billing.v1.ExclusionR\texclusion\"\x17\n" +
	"\x15ListExclusionsRequest\"K\n" +
	"\x13ListExclusionsReply\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.platform_billing.v1.ExclusionR\x05items\"(\n" +
	"\x16DeleteExclusionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x16\n" +
	"\x14DeleteExclusionReply\"3\n" +
	"\x12ClosePeriodRequest\x12\x1d\n" +
	"\n" +
	"period_end\x18\x01 \x01(\tR\tperiodEnd\"X\n" +
	"\x10ClosePeriodReply\x12!\n" +
	"\fclosed_count\x18\x01 \x01(\x05R\vclosedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\"x\n" +
	"\x17GetBillingReportRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12!\n" +
	"\fperiod_start\x18\x02 \x01(\tR\vperiodStart\x12\x1d\n" +
	"\n" +
	"period_end\x18\x03 \x01(\tR\tperiodEnd\"S\n" +
	"\x15GetBillingReportReply\x12:\n" +
	"\x06report\x18\x01 \x01(\v2\".platform_billing.v1.BillingReportR\x06report2\xa3\x04\n" +
	"\x16PlatformBillingService\x12i\n" +
	"\x0fCreateExclusion\x12+.platform_billing.v1.CreateExclusionRequest\x1a).platform_billing.v1.CreateExclusionReply\x12f\n" +
	"\x0eListExclusions\x12*.platform_billing.v1.ListExclusionsRequest\x1a(.platform_billing.v1.ListExclusionsReply\x12i\n" +
	"\x0fDeleteExclusion\x12+.platform_billing.v1.DeleteExclusionRequest\x1a).platform_billing.v1.DeleteExclusionReply\x12]\n" +
	"\vClosePeriod\x12'.platform_billing.v1.ClosePeriodRequest\x1a%.platform_billing.v1.ClosePeriodReply\x12l\n" +
	"\x10GetBillingReport\x12,.platform_billing.v1.GetBillingReportRequest\x1a*.platform_billing.v1.GetBillingReportReplyBTZRgithub.com/makesalekz/platform-billing/api/platform_billing/v1;platform_billing_v1b\x06proto3"

var (
	file_api_platform_billing_v1_platform_billing_proto_rawDescOnce sync.Once
	file_api_platform_billing_v1_platform_billing_proto_rawDescData []byte
)

func file_api_platform_billing_v1_platform_billing_proto_rawDescGZIP() []byte {
	file_api_platform_billing_v1_platform_billing_proto_rawDescOnce.Do(func() {
		file_api_platform_billing_v1_platform_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_platform_billing_v1_platform_billing_proto_rawDesc), len(file_api_platform_billing_v1_platform_billing_proto_rawDesc)))
	})
	return file_api_platform_billing_v1_platform_billing_proto_rawDescData
}

var file_api_platform_billing_v1_platform_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_platform_billing_v1_platform_billing_proto_goTypes = []any{
	(*CreateExclusionRequest)(nil),  // 0: platform_billing.v1.CreateExclusionRequest
	(*CreateExclusionReply)(nil),    // 1: platform_billing.v1.CreateExclusionReply
	(*ListExclusionsRequest)(nil),   // 2: platform_billing.v1.ListExclusionsRequest
	(*ListExclusionsReply)(nil),     // 3: platform_billing.v1.ListExclusionsReply
	(*DeleteExclusionRequest)(nil),  // 4: platform_billing.v1.DeleteExclusionRequest
	(*DeleteExclusionReply)(nil),    // 5: platform_billing.v1.DeleteExclusionReply
	(*ClosePeriodRequest)(nil),      // 6: platform_billing.v1.ClosePeriodRequest
	(*ClosePeriodReply)(nil),        // 7: platform_billing.v1.ClosePeriodReply
	(*GetBillingReportRequest)(nil), // 8: platform_billing.v1.GetBillingReportRequest
	(*GetBillingReportReply)(nil),   // 9: platform_billing.v1.GetBillingReportReply
	(*Exclusion)(nil),               // 10: platform_billing.v1.Exclusion
	(*BillingReport)(nil),           // 11: platform_billing.v1.BillingReport
}
var file_api_platform_billing_v1_platform_billing_proto_depIdxs = []int32{
	10, // 0: platform_billing.v1.CreateExclusionReply.exclusion:type_name -> platform_billing.v1.Exclusion
	10, // 1: platform_billing.v1.ListExclusionsReply.items:type_name -> platform_billing.v1.Exclusion
	11, // 2: platform_billing.v1.GetBillingReportReply.report:type_name -> platform_billing.v1.BillingReport
	0,  // 3: platform_billing.v1.PlatformBillingService.CreateExclusion:input_type -> platform_billing.v1.CreateExclusionRequest
	2,  // 4: platform_billing.v1.PlatformBillingService.ListExclusions:input_type -> platform_billing.v1.ListExclusionsRequest
	4,  // 5: platform_billing.v1.PlatformBillingService.DeleteExclusion:input_type -> platform_billing.v1.DeleteExclusionRequest
	6,  // 6: platform_billing.v1.PlatformBillingService.ClosePeriod:input_type -> platform_billing.v1.ClosePeriodRequest
	8,  // 7: platform_billing.v1.PlatformBillingService.GetBillingReport:input_type -> platform_billing.v1.GetBillingReportRequest
	1,  // 8: platform_billing.v1.PlatformBillingService.CreateExclusion:output_type -> platform_billing.v1.CreateExclusionReply
	3,  // 9: platform_billing.v1.PlatformBillingService.ListExclusions:output_type -> platform_billing.v1.ListExclusionsReply
	5,  // 10: platform_billing.v1.PlatformBillingService.DeleteExclusion:output_type -> platform_billing.v1.DeleteExclusionReply
	7,  // 11: platform_billing.v1.PlatformBillingService.ClosePeriod:output_type -> platform_billing.v1.ClosePeriodReply
	9,  // 12: platform_billing.v1.PlatformBillingService.GetBillingReport:output_type -> platform_billing.v1.GetBillingReportReply
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_platform_billing_v1_platform_billing_proto_init() }
func file_api_platform_billing_v1_platform_billing_proto_init() {
	if File_api_platform_billing_v1_platform_billing_proto != nil {
		return
	}
	file_api_platform_billing_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_platform_billing_v1_platform_billing_proto_rawDesc), len(file_api_platform_billing_v1_platform_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_platform_billing_v1_platform_billing_proto_goTypes,
		DependencyIndexes: file_api_platform_billing_v1_platform_billing_proto_depIdxs,
		MessageInfos:      file_api_platform_billing_v1_platform_billing_proto_msgTypes,
	}.Build()
	File_api_platform_billing_v1_platform_billing_proto = out.File
	file_api_platform_billing_v1_platform_billing_proto_goTypes = nil
	file_api_platform_billing_v1_platform_billing_proto_depIdxs = nil
}
