// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Commission is the predicate function for commission builders.
type Commission func(*sql.Selector)

// Exclusion is the predicate function for exclusion builders.
type Exclusion func(*sql.Selector)

// SaleEvent is the predicate function for saleevent builders.
type SaleEvent func(*sql.Selector)
